import type { SecretaryResult } from './types';
import { receiptViewModel } from './receipt';

/** The operation receipt is separate from the todo's own completion state. */
export function secretaryResultStatus(result: SecretaryResult): string {
  return receiptViewModel(result).operationLabel;
}

/** Only emotionally scoped clauses can enter receipts. Unknown prose stays out. */
export function secretaryAcknowledgement(reply: string | undefined): string {
  const sentences = (reply ?? '').trim().split(/(?<=[。！？!?])|\n/u);
  const emotionalClause = /^(?:(?:你|您|今天|你今天|您今天)?(?:已经)?(?:真的|确实|很|有点|挺|太)?(?:累了?|疲惫了?|辛苦了|不容易了?)|(?:听起来|看起来)(?:你|您|今天|你今天|您今天)?(?:已经)?(?:真的|确实|很|有点|挺|太)?(?:累了?|疲惫了?|辛苦了|不容易了?)|(?:先|可以先)?(?:歇一会儿|休息一会儿|缓口气|慢慢来)|(?:别|不用|不必)着急|我在|收到|嗯)$/u;
  for (const sentence of sentences) {
    if (sentence.length > 100 || /[？?]$/u.test(sentence)) continue;
    const clauses = sentence.trim().replace(/[。！!]+$/u, '').split(/[，,；;]/u).map(s => s.trim());
    const safe: string[] = [];
    for (const clause of clauses) { if (!emotionalClause.test(clause)) break; safe.push(clause); }
    if (safe.length) return safe.join('，') + (/！|!$/u.test(sentence) ? '！' : '。');
  }
  return '';
}

/** Questions come from the actual missing fields or candidates, never raw planner prose. */
export function secretaryFollowupQuestion(results: SecretaryResult[]): string {
  const result = results.find(item => item.status === 'needs-input');
  if (!result) return '';
  const receipt = receiptViewModel(result);
  if (receipt.missingFields.includes('purpose')) return '记成待办还是日记？';
  if (result.candidates?.length) return '你指的是哪一项？从下面选一下。';
  if (result.stepCandidates?.length) return '你想处理哪一步？从下面选一下。';
  if (result.action.kind === 'todo.create') {
    if (result.detail === '想提醒你哪件事？') return result.detail;
    if (!result.action.title) return '要记哪件事？';
    if (result.action.reminder && (!result.action.date || !result.action.time)) return !result.action.date && !result.action.time ? '哪一天、几点提醒你？' : !result.action.date ? '哪一天提醒你？' : '几点提醒你？';
  }
  // detail is generated by execution code, not the model reply.
  return result.detail ?? '';
}
