import {createRoot} from 'react-dom/client';
import {db} from '../../src/db';
import {useAuthStore} from '../../src/store/auth-store';
import {fakeCharacter} from './world-harness';
import {ChatQualityPanel} from '../../src/components/settings/ChatQualityPanel';
import {assessExpressionSignals,expressionDirection} from '../../src/lib/chat-expression-guidance';
import {detectHumanTurn,buildCharacterVoiceCard} from '../../src/lib/chat-humanizer';
import {inspectChatOutput} from '../../src/lib/chat-output-quality';
import {recordQualityEvent,recordChatQuality,chatQualityReport,clearChatQuality} from '../../src/lib/chat-quality-metrics';
import {voiceCacheStatus} from '../../src/lib/chat/voice-sample-cache';
import {EXPRESSION_SCENARIOS,EVALUATION_PERSONAS,runExpressionEvaluation,evaluationSummary} from '../../src/lib/chat-expression-evaluation';
import {EXPRESSION_SIGNAL_CORPUS} from '../../src/lib/chat-expression-corpus';
import {DIALOGUE_TRAJECTORIES} from '../../src/lib/chat-evaluation-trajectories';
const owner='quality-test-owner';let root:ReturnType<typeof createRoot>|undefined;
async function run(){
  let checks=0;const ok=(value:unknown,label:string)=>{if(!value)throw Error(label);checks++;console.log('ok '+label);};
  await db.delete();await db.open();useAuthStore.getState().login(owner,'测试','isolated-test-key','');clearChatQuality();
  const role=fakeCharacter('quality-role','小林',owner,{systemPrompt:'称呼：小友\n判断习惯：先核对事实\n对话样本：用户说你好 → 你说在呢，小友'});await db.characters.add(role);
  const mixed=assessExpressionSignals('我累死了，那个报告你帮我看看呗');
  ok(EXPRESSION_SIGNAL_CORPUS.length===150,'fixed signal corpus contains 150 contrasting utterances');
  for(const entry of EXPRESSION_SIGNAL_CORPUS){const signals=assessExpressionSignals(entry.text);ok(signals.request===entry.request&&(!entry.situation||signals.situation===entry.situation),`fixed utterance: ${entry.text}`);}
  ok(mixed.request&&mixed.situation==='tired'&&mixed.emotionConfidence>=.8,'request and tiredness coexist');
  ok(detectHumanTurn('那个报告你帮我看看呗').mode==='request','postposed request chooses request action');
  for(const text of ['我不难过','她最近很难过','他说“我很累”','如果我很累呢','怎么安慰难过的人？'])ok(assessExpressionSignals(text).situation==='neutral',`no false personal feeling: ${text}`);
  for(const text of ['不用分析，陪我聊聊','不要帮我写报告','他说“帮我分析一下”'])ok(!assessExpressionSignals(text).request,`no invented request: ${text}`);
  ok(expressionDirection(assessExpressionSignals('难过')).includes('线索不足'),'uncertain emotion does not dictate tone');
  ok(inspectChatOutput('哈哈😂',{mode:'private',persona:'表情：不用 emoji'}).check.issue==='voice-conflict','explicit emoji preference has a local check');
  ok(inspectChatOutput('哈哈😂',{mode:'private',persona:'表情：不用 emoji',userMessage:'加个表情'}).check.ok,'current user expression choice overrides preference');
  ok(inspectChatOutput('老板，你看这个',{mode:'private',persona:'禁用称呼：老板、宝贝'}).check.issue==='voice-conflict','explicit forbidden address detected');
  ok(inspectChatOutput('嗯',{mode:'private',persona:'温柔'}).check.ok,'personality never forces padding or catchphrase');
  ok(voiceCacheStatus(role)==='authored'&&buildCharacterVoiceCard(role).includes('小友'),'authored voice stays authoritative');
  recordQualityEvent(owner,{mode:'proactive',retries:1,blocked:true,streamed:false,issue:'generic',durationMs:50});
  recordQualityEvent(owner,{mode:'group',retries:0,blocked:false,streamed:false});
  recordQualityEvent(owner,{mode:'private',retries:0,blocked:false,streamed:true,issue:'voice-conflict'});
  const report=chatQualityReport();ok(report.byMode.proactive.blocked===1&&report.byMode.group.checked===1&&report.byMode.private.streamedUnresolved===1,'mode diagnostics distinguish retries, blockage and visible issues');
  ok(!JSON.stringify(report).includes('老板'),'diagnostics store no message text');
  useAuthStore.getState().login('other-owner','别人','isolated-test-key','');
  recordQualityEvent(owner,{mode:'group',retries:0,blocked:false,streamed:false});ok(chatQualityReport().events.length===0,'late diagnostics cannot cross account boundary');
  useAuthStore.getState().login(owner,'测试','isolated-test-key','');ok(chatQualityReport().events.length===3,'original account restores only own diagnostics');
  recordChatQuality(owner,'（顿了顿，把手机放下）今天\n路过书店','今天路过书店',0,true,{durationMs:200,firstVisibleMs:50,streamed:true});
  const measured=chatQualityReport();
  ok(measured.samples[0].actionRemovedChars!>0&&measured.samples[0].collapsedLineBreaks===1&&measured.samples[0].introducedChineseSpaces===0,'cleanup metrics distinguish actions, newlines and introduced Chinese spaces');
  ok(measured.byMode.private.averageFirstVisibleMs===50,'first visible latency uses actual publication evidence');
  let calls=0;const original=window.fetch;const prompts:string[]=[],payloads:any[]=[];
  window.fetch=async(_url,init)=>{const payload=JSON.parse(String(init?.body));payloads.push(payload);prompts.push(payload.messages[0].content);calls++;return new Response(JSON.stringify({usage:{prompt_tokens:100,completion_tokens:20},choices:[{message:{content:`我想听你继续说这件事，第${calls}句。`},finish_reason:'stop'}]}),{headers:{'Content-Type':'application/json'}});};
  try {
    const roles=EVALUATION_PERSONAS.map((p,i)=>({...role,id:`eval-${i}`,name:p.name,systemPrompt:p.prompt}));
    const matrix=await runExpressionEvaluation(roles,15,new AbortController().signal,()=>{});
    ok(matrix.complete&&matrix.rows.length===75&&calls===75,'five-role fixed matrix produces exactly 75 actual task calls');
    ok(EXPRESSION_SCENARIOS.length===15&&prompts.every(p=>p.includes('[人物声音卡]')),'each evaluation call receives authoritative voice context');
    ok(evaluationSummary(matrix).semanticStatus==='unrated','local success never pretends to be semantic acceptance');
    matrix.rows[0].ratings={naturalness:5,identity:0,context:5,truth:5};ok(evaluationSummary(matrix).rated===0,'partial manual scoring stays unaccepted');
    matrix.rows.forEach(r=>{r.ratings={naturalness:4,identity:4,context:4,truth:5};});ok(evaluationSummary(matrix).rated===75,'complete ratings aggregate explicitly');
    const longStart=payloads.length;
    const long=await runExpressionEvaluation([role],30,new AbortController().signal,()=>{});ok(long.rows.length===30&&long.complete,'30-round continuity fixture completes without role rewrites');
    ok(payloads.slice(longStart).every(p=>p.messages.length<=14&&p.messages.slice(1,-1).every((m:any)=>m.content.length<=1200)),'continuous evaluator shares production twelve-item history and per-message text limit');
    ok(payloads[longStart+29].messages[1].content===EXPRESSION_SCENARIOS[23%EXPRESSION_SCENARIOS.length],'thirtieth evaluation turn retains six complete recent turns rather than eighteen raw history items');
    const start=calls;
    const repairTrajectory=DIALOGUE_TRAJECTORIES.find(trajectory=>trajectory.id==='repair')!;
    const small=await runExpressionEvaluation([role],60,new AbortController().signal,()=>{},{trajectoryId:repairTrajectory.id});
    const smallPayloads=payloads.slice(start);
    ok(calls-start===6&&small.complete&&small.budget?.calls===6,'small coherent trajectory has exactly six calls despite requested sixty rounds');
    ok(smallPayloads.every(p=>p.model==='deepseek-flash'&&p.max_tokens===320),'small test locks Flash and output cap');
    ok(smallPayloads.every(p=>/\[\/人物声音卡\]\s*\[手机私聊表达契约\]/u.test(p.messages[0].content)),'actual evaluator model requests put the protected character voice immediately before one shared contract');
    ok(smallPayloads[1].messages.some((m:any)=>m.role==='assistant'&&m.content===small.rows[0].reply),'next turn feeds actual prior reply rather than a fixture answer');
    ok(small.rows.every((r,i)=>r.input===repairTrajectory.turns[i].input),'trajectory follows coherent user turns');
    ok(!JSON.stringify(smallPayloads).includes(repairTrajectory.turns[0].focus),'human assessment focus is never fed to actor model');
    const freshStart=calls;
    const freshTrajectory=DIALOGUE_TRAJECTORIES.find(trajectory=>trajectory.id==='smalltalk')!;
    const fresh=await runExpressionEvaluation([role],60,new AbortController().signal,()=>{},{trajectoryId:freshTrajectory.id});
    const freshPayloads=payloads.slice(freshStart);
    ok(fresh.complete&&fresh.rows.length===6&&calls-freshStart===6,'the new everyday scene runs as one bounded six-turn sequence');
    ok(fresh.rows.every((row,index)=>row.input===freshTrajectory.turns[index].input)&&freshPayloads.every(p=>p.max_tokens===320),'new scene inputs and output budget remain fixed for reproducible comparison');
    ok(freshTrajectory.turns.every(turn=>!JSON.stringify(freshPayloads).includes(turn.focus)),'new scene review notes do not guide the actor toward expected test answers');
    ok(small.rows[1].attention?.preferences.adviceStyle==='listen'&&smallPayloads[2].messages[0].content.includes('未经请求不要立刻给解决方案'),'repair trajectory carries natural no-solution expression into the following clarification');
    const attentionStart=payloads.length;
    const listeningTest=await runExpressionEvaluation([role],60,new AbortController().signal,()=>{},{trajectoryId:'tired'});
    const listeningPayloads=payloads.slice(attentionStart);
    ok(listeningTest.complete&&listeningTest.rows.length===6&&listeningTest.rows[1].attention?.preferences.adviceStyle==='listen','continuous evaluation carries actual listening attention between replies');
    ok(listeningPayloads[2].messages[0].content.includes('未经请求不要立刻给解决方案'),'next evaluation request receives the same persisted attention guidance as production');
    ok(listeningTest.rows[2].attention?.turnCount===3&&listeningTest.rows[5].attention?.topicStatus==='closed','evaluation state counts successful turns and recognizes final goodbye');
    ok(listeningPayloads.every(p=>p.messages[0].content.indexOf('[本会话的连续注意力]')<p.messages[0].content.indexOf('[人物声音卡]')),'shared compiler places attention before the authoritative tail voice card');
    ok(matrix.rows.find(r=>r.role===roles[1].name)?.attention?.turnCount===1,'each evaluated character begins with an independent attention state');
    ok(evaluationSummary(small).usage.inputTokens===600&&evaluationSummary(small).usage.outputTokens===120&&evaluationSummary(small).usage.unknownCalls===0,'actual reported usage aggregates without estimates');
    small.rows[0].usage=undefined;
    ok(evaluationSummary(small).usage.unknownCalls===1&&evaluationSummary(small).usage.inputTokens===500,'missing usage remains unknown rather than zero-cost');
    small.rows.forEach(r=>{r.ratings={naturalness:5,identity:5,context:5,truth:5};});small.complete=false;
    ok(evaluationSummary(small).semanticStatus==='unrated','partial run cannot count as fully rated acceptance');
    const cancel=new AbortController();cancel.abort();const before=calls;await runExpressionEvaluation([role],15,cancel.signal,()=>{});ok(calls===before,'cancelled evaluation performs zero model calls');
    const previousFetch=window.fetch;let truncatedCalls=0;
    window.fetch=async()=>{truncatedCalls++;return new Response(JSON.stringify({usage:{prompt_tokens:100,completion_tokens:320},choices:[{message:{content:'还没讲完'},finish_reason:'length'}]}),{headers:{'Content-Type':'application/json'}});};
    const cut=await runExpressionEvaluation([role],15,new AbortController().signal,()=>{});
    ok(truncatedCalls===1&&!cut.complete&&cut.rows[0].truncated&&!!cut.rows[0].error,'truncated output stops further paid evaluation calls and remains incomplete');
    cut.complete=true;cut.rows[0].ratings={naturalness:5,identity:5,context:5,truth:5};
    ok(evaluationSummary(cut).truncated===1&&evaluationSummary(cut).semanticStatus==='unrated','even fully rated truncated rows cannot prove semantic acceptance');
    window.fetch=async()=>new Response(JSON.stringify({choices:[{message:{content:''},finish_reason:'stop'}]}),{headers:{'Content-Type':'application/json'}});
    const empty=await runExpressionEvaluation([role],15,new AbortController().signal,()=>{});
    ok(empty.rows.length===1&&!empty.complete&&!!empty.rows[0].error,'empty visible answer stops evaluation without pretending generation completed');
    window.fetch=previousFetch;
    let multipartCalls=0;const multipartPayloads:any[]=[];
    window.fetch=async(_url,init)=>{multipartCalls++;multipartPayloads.push(JSON.parse(String(init?.body)));return new Response(JSON.stringify({choices:[{message:{content:'嗯---我听着。---这个点说清了。---那就接着说。'},finish_reason:'stop'}]}),{headers:{'Content-Type':'application/json'}});};
    const multipart=await runExpressionEvaluation([role],8,new AbortController().signal,()=>{});
    ok(multipart.complete&&multipartCalls===8&&multipartPayloads[7].messages.length===14,'four-bubble evaluation replies still retain six complete user/reply turns with exactly one call per turn');
    ok(multipartPayloads[7].messages[2].content==='嗯\n---\n我听着。\n---\n这个点说清了。\n---\n那就接着说。','evaluation history uses the same grouped bubble separator and source order as production');
    window.fetch=previousFetch;
    ok(await db.messages.count()===0&&await db.sessions.count()===0&&(await db.characters.get(role.id))?.systemPrompt===role.systemPrompt,'evaluation writes no chats, sessions or persona changes');
    let published=0;
    window.fetch=async()=>{useAuthStore.getState().login('other-owner','别人','isolated-test-key','');return new Response(JSON.stringify({choices:[{message:{content:'这是旧账号的迟到回复'},finish_reason:'stop'}]}),{headers:{'Content-Type':'application/json'}});};
    const switched=await runExpressionEvaluation([role],15,new AbortController().signal,()=>published++);
    ok(switched.rows.length===0&&published===0,'account switch rejects late evaluation replies and progress');
    useAuthStore.getState().login(owner,'测试','isolated-test-key','');
  } finally{window.fetch=original;}
  clearChatQuality();
  recordQualityEvent(owner,{mode:'private',issue:'self-report-risk',retries:0,blocked:false,streamed:true});
  const sourceRiskMetrics=chatQualityReport();
  ok(sourceRiskMetrics.byMode.private.issues['self-report-risk']===1&&sourceRiskMetrics.byMode.private.streamedUnresolved===1,'visible self-report risk is counted without being relabelled as an improved reply');
  ok(sourceRiskMetrics.byMode.private.improvedAfterRetry===0&&sourceRiskMetrics.events[0].issue==='self-report-risk','new source-risk enum survives diagnostic storage and aggregation');
  ok(!JSON.stringify(sourceRiskMetrics).includes('盯着锁屏'),'source-risk diagnostics retain no draft text or persona evidence');
    clearChatQuality();
    recordQualityEvent(owner,{mode:'private',issue:'user-source-risk',retries:1,blocked:false,streamed:false,improvedAfterRetry:true});
    const teasingMetrics=chatQualityReport();
    ok(teasingMetrics.byMode.private.issues['user-source-risk']===1&&teasingMetrics.events[0].issue==='user-source-risk','remembered user attribution risk survives diagnostic storage and aggregation');
  return {checks};
}
function mount(){root?.unmount();root=createRoot(document.getElementById('app')!);root.render(<ChatQualityPanel open onClose={()=>root?.render(<div>已返回</div>)}/>);}
(window as any).qualityTest={run,mount};
