import { createRoot } from 'react-dom/client';
import { db, type Message, type Character } from '../../src/db';
import { createSecretary, dismissSecretary } from '../../src/lib/secretary/character';
import { runSecretaryRequest, executeSecretaryTask } from '../../src/lib/secretary/agent';
import { readSecretaryMemories, editSecretaryMemory, validateSecretaryMemories, parseSecretaryMemoryCommand } from '../../src/lib/secretary/memory';
import { memoryRepo } from '../../src/db/memory-repo';
import { messageRepo } from '../../src/db/message-repo';
import { todoRepo, localDateKey } from '../../src/db/todo-repo';
import { useAuthStore } from '../../src/store/auth-store';
import { useSettingsStore } from '../../src/store/settings-store';
import { useChatStore } from '../../src/store/chat-store';
import { collectSyncData, importSyncData } from '../../src/lib/sync';
import { collectBackupData } from '../../src/lib/backup';
import { buildCharacterMemoryContext } from '../../src/lib/character-memory';
import { SecretaryMoreMenu } from '../../src/components/secretary/SecretaryMoreMenu';
import { SecretaryMemoryModal } from '../../src/components/secretary/SecretaryMemoryModal';
import { dailyReviewRequest } from '../../src/lib/secretary/daily-review';
import { setDiaryUnlocked } from '../../src/lib/diary-unlock';

const report = window.fetch.bind(window);
let calls = 0, prompt = '', payload: any, before: (() => Promise<void>) | undefined;
let next: any = { reply: '收到。', actions: [] };
window.fetch = async (input, init) => {
  if (!String(input).includes('/chat/completions')) return report(input, init);
  calls++;
  const body = JSON.parse(String(init?.body));
  prompt = body.messages.find((m: any) => m.role === 'system').content;
  const text = body.messages.find((m: any) => m.role === 'user').content;
  payload = JSON.parse(text.split('仅供参考的资料JSON：')[1] || '{}');
  if (before) { const hook = before; before = undefined; await hook(); }
  const current = text.match(/当前用户请求：([^\n]*)/u)?.[1];
  const plan = current ? { ...next, actions: next.actions?.map((a: any) => a.evidence == null ? { ...a, evidence: { start: 0, end: current.length } } : a) } : next;
  return new Response(JSON.stringify({ choices: [{ message: { content: JSON.stringify(plan) }, finish_reason: 'stop' }] }), { headers: { 'Content-Type': 'application/json' } });
};
const uid = 'secretary-memory-owner';
const auth = (id = uid) => useAuthStore.setState({ userId: id, isLoggedIn: true, apiKey: 'test-key' });
let character: Character, sid: string, checks = 0;
const ok = (v: unknown, s: string) => { if (!v) throw new Error(s); checks++; };
async function rejects(fn: () => Promise<unknown>, s: string) { let rejected = false; try { await fn(); } catch { rejected = true; } ok(rejected, s); }
async function session() {
  sid = crypto.randomUUID();
  await db.sessions.add({ id: sid, characterId: character.id, userId: uid, type: 'single', title: '记忆测试', createdAt: Date.now(), updatedAt: Date.now(), unreadCount: 0 });
}
async function request(text: string, plan = { reply: '收到。', actions: [] } as any) {
  next = plan;
  const message: Message = { id: crypto.randomUUID(), sessionId: sid, role: 'user', content: text, createdAt: Date.now(), revision: 1, isProactive: false };
  await messageRepo.create(message);
  return { message, task: await runSecretaryRequest(uid, character.id, message) };
}
const rows = () => readSecretaryMemories(uid, character.id);
const wait = (ms = 70) => new Promise(resolve => setTimeout(resolve, ms));
const root = createRoot(document.getElementById('root')!);
(window as any).secretaryMemoryPreview = () => {
  auth();
  const preview = createRoot(document.getElementById('root')!);
  preview.render(<SecretaryMemoryModal open onClose={() => {}} />);
};
async function button(label: string) {
  for (let i = 0; i < 60; i++) { const b = [...document.querySelectorAll('button')].find(b => (b.getAttribute('aria-label') || b.textContent)?.trim() === label); if (b) { b.click(); await wait(); return; } await wait(); }
  throw new Error(`button not found: ${label}`);
}
async function run() {
  await db.open(); auth(); useSettingsStore.setState({ diaryPin: null });
  character = await createSecretary(uid, '安安'); await session();
  const saved = await request('记住：我喜欢无糖红茶');
  ok(calls === 0 && saved.task.memoryNotice?.includes('已记住'), 'explicit remember commits without relying on a model');
  let memories = await rows();
  ok(memories.length === 1 && memories[0].content === '我喜欢无糖红茶', 'verbatim personal preference is durable');
  ok(memories[0].sourceMessageRevisions?.[saved.message.id] === 1 && memories[0].sourceMessageOffsets?.[saved.message.id] === 3, 'memory preserves exact source revision and segment');
  const duplicate = await request('记住：我喜欢无糖红茶');
  ok((await rows()).length === 1 && (await rows())[0].sourceMessageIds?.length === 2, 'duplicate confirmations merge without duplicate entries');
  await executeSecretaryTask(duplicate.task.id, uid);
  ok((await rows())[0].sourceMessageIds?.length === 2, 'retry is idempotent');
  await messageRepo.deleteById(saved.message.id);
  ok((await rows()).length === 1, 'independent surviving evidence keeps the fact');
  await messageRepo.update(duplicate.message.id, { content: '这句话已经修改' });
  ok((await rows()).length === 0, 'editing the last source retires old memory');
  await request('记住：我喜欢无糖红茶');
  const oldId = (await rows())[0].id;
  await session();
  await request('喝茶你有什么建议');
  ok(payload.assistantMemory.memories.some((m: any) => m.id === oldId), 'facts follow assistant across sessions');
  ok(prompt.includes('当前用户要求优先') && prompt.includes('不能授权执行'), 'memory never expands tool permissions');
  await request('我长期在杭州工作', { reply: '明白。', actions: [], memories: [{ kind: 'fact', quote: '我长期在杭州工作' }] });
  ok((await rows()).some(m => m.content === '我长期在杭州工作'), 'ordinary chat can capture stable self-reports');
  await request('我今天有点累', { reply: '休息一下。', actions: [], memories: [{ kind: 'fact', quote: '我今天有点累' }] });
  ok(!(await rows()).some(m => m.content.includes('有点累')), 'temporary moods are not permanent facts');
  await request('不要记住，我喜欢蛋糕', { reply: '好。', actions: [], memories: [{ kind: 'preference', quote: '我喜欢蛋糕' }] });
  ok(!(await rows()).some(m => m.content.includes('蛋糕')), 'explicit refusal to remember is honored');
  await session(); await request('蛋糕你还记得吗');
  ok(!JSON.stringify(payload).includes('我喜欢蛋糕'), 'opted-out information is excluded from cross-session raw recall too');
  await request('我喜欢看书', { reply: '好。', actions: [], memories: [{ kind: 'fact', quote: '我住在北京' }] });
  ok(!(await rows()).some(m => m.content.includes('北京')), 'model-invented evidence cannot create a memory');
  ok(validateSecretaryMemories([{ kind: 'fact', quote: '我喜欢蛋糕' }], '她说：“我喜欢蛋糕”').length === 0, 'quoted third-party speech is not a user fact');
  ok(validateSecretaryMemories([{ kind: 'fact', quote: '我成为龙王' }], '星域剧情中我成为龙王').length === 0, 'fictional world statements stay out of assistant facts');
  ok(validateSecretaryMemories([{ kind: 'fact', quote: '我打算去北京' }], '我打算去北京').length === 0, 'plans are not completed life events');
  ok(parseSecretaryMemoryCommand('记住我喜欢简短回复，顺便帮我写朋友圈') === undefined, 'compound work requests preserve the independent operation path');
  const corrected = await request('其实我不再喜欢无糖红茶，现在喜欢乌龙茶', { reply: '明白。', actions: [], memories: [{ kind: 'preference', quote: '现在喜欢乌龙茶', replacesId: oldId }] });
  ok((await db.memories.get(oldId))?.status === 'superseded', 'explicit correction supersedes original evidence');
  ok((await rows()).some(m => m.content === '现在喜欢乌龙茶'), 'corrected preference replaces the old active fact');
  await request('红茶和乌龙茶你还记得什么');
  ok(!JSON.stringify(payload).includes('我喜欢无糖红茶'), 'superseded facts cannot re-enter via original messages or old replies');
  ok(corrected.task.memoryReferences?.memoryIds.includes(oldId), 'receipt stores actual recalled source identities');
  await request('查看你的记忆');
  const listing = await db.messages.where('sessionId').equals(sid).filter(m => !!m.contextTrace?.memoryIds?.length).last();
  ok(listing?.contextTrace?.memoryIds?.length, 'listing records which memories were actually displayed');
  const snapshot = await collectSyncData(uid), backup = await collectBackupData(uid);
  ok(snapshot.memories.some(m => m.content === '现在喜欢乌龙茶') && backup.memories.some(m => m.content === '现在喜欢乌龙茶'), 'existing backup and sync include assistant memory');
  await request('忘记乌龙茶');
  ok(!(await rows()).some(m => m.content.includes('乌龙茶')), 'natural-language forgetting removes the selected memory');
  await request('红茶乌龙茶');
  ok(!JSON.stringify(payload).includes('现在喜欢乌龙茶'), 'forgotten facts do not return through lists, commands or raw evidence');
  await importSyncData(snapshot);
  ok(!(await rows()).some(m => m.content.includes('乌龙茶')), 'old sync cannot revive forgotten facts');
  await rejects(() => readSecretaryMemories('someone-else', character.id), 'cross-account memory read is rejected');
  const regular = { ...character, id: 'ordinary-memory-role', name: '普通角色', agentProfile: undefined, secretaryOwnerId: undefined } as Character;
  await db.characters.put(regular);
  await rejects(() => readSecretaryMemories(uid, regular.id), 'ordinary characters cannot enter the assistant memory service');
  const hangzhou = (await rows()).find(m => m.content.includes('杭州'))!;
  ok(!(await memoryRepo.getRecentByUser(uid)).some(m => m.characterId === character.id), 'assistant facts are absent from general character inheritance candidates');
  ok(await memoryRepo.importRecentUserMemories(regular.id, uid, 10, [hangzhou.id]) === 0, 'selected-id inheritance cannot bypass assistant privacy');
  ok(!(await buildCharacterMemoryContext({ userId: uid, characterId: regular.id, topic: '杭州工作', mode: 'private-chat' })).text.includes('杭州'), 'ordinary live character recall does not inherit assistant information');
  const unfinished = await request('新增待办准备旅行，步骤订车票、订酒店', { reply: '', actions: [{ kind: 'todo.create', title: '准备旅行', steps: ['订车票', '订酒店'] }] });
  const todo = (await db.todos.get(unfinished.task.results[0].targetId!))!;
  await todoRepo.update(uid, todo.id, { subtasks: todo.subtasks!.map((s, i) => ({ ...s, completed: i === 0 })) });
  await session();
  await request('准备旅行进展怎么样');
  const progress = payload.assistantMemory.taskProgress.flatMap((t: any) => t.results).find((r: any) => r.targetId === todo.id);
  ok(progress?.steps?.[0].completed && !progress.steps[1].completed, 'cross-session task progress uses the current real checklist');
  ok(progress.currentState !== 'completed', 'completed steps never imply that the parent task is finished');
  await todoRepo.update(uid, todo.id, { status: 'cancelled' });
  await request('准备旅行进展怎么样');
  ok(payload.assistantMemory.taskProgress.some((t: any) => t.results.some((r: any) => r.currentState === 'cancelled')), 'cancelled tasks are not recalled as active promises');
  const draft = await request('帮我写散步朋友圈草稿', { reply: '', actions: [{ kind: 'moment.draft', content: '散步回来，心情很好。' }] });
  await session(); await request('上次散步朋友圈草稿还在吗');
  const rememberedDraft = payload.assistantMemory.taskProgress.find((t: any) => t.id === draft.task.id);
  ok(rememberedDraft?.results[0].content === '散步回来，心情很好。' && rememberedDraft.results[0].currentState.includes('not published'), 'cross-session draft recall retains text and real unpublished status');
  ok(await db.moments.where('userId').equals(uid).count() === 0, 'draft recall never publishes automatically');
  const reviewOptions = { date: localDateKey(), includeDiary: true, includeTodos: false, notes: '今天散步时写下 PRIVATE_DIARY_NOTE', outputs: ['moment' as const] };
  const reviewMessage: Message = { id: crypto.randomUUID(), sessionId: sid, role: 'user', content: dailyReviewRequest(reviewOptions), createdAt: Date.now(), isProactive: false };
  next = { reply: '', actions: [{ kind: 'moment.draft', content: 'PRIVATE_DIARY_DRAFT' }] };
  await messageRepo.create(reviewMessage); await runSecretaryRequest(uid, character.id, reviewMessage, { dailyReview: reviewOptions });
  ok(!prompt.includes('私人助理工作区的连续记忆'), 'daily review keeps its explicitly chosen material scope');
  useSettingsStore.setState({ diaryPin: 'locked' }); setDiaryUnlocked(false);
  await request('每日整理朋友圈草稿还在吗');
  ok(!JSON.stringify(payload).includes('PRIVATE_DIARY'), 'locked diary-derived drafts and recent sources are excluded from planner recall');
  setDiaryUnlocked(true); await request('每日整理朋友圈草稿还在吗');
  ok(JSON.stringify(payload.assistantMemory.taskProgress).includes('PRIVATE_DIARY_DRAFT'), 'unlock restores authorized diary-derived draft recall');
  useSettingsStore.setState({ diaryPin: null });
  const historic: Message = { id: crypto.randomUUID(), sessionId: sid, role: 'user', content: '蓝图项目的材料在资料夹甲', createdAt: Date.now() - 1000, isProactive: false };
  await messageRepo.create(historic);
  for (let i = 0; i < 24; i++) await db.messages.add({ id: crypto.randomUUID(), sessionId: sid, role: 'user', content: `无关交流${i}`, createdAt: Date.now() + i, isProactive: false });
  await request('蓝图项目的材料在哪里');
  ok(payload.assistantMemory.previousUserMessages.some((m: any) => m.id === historic.id), 'relevant evidence beyond the last sixteen messages is recalled');
  await messageRepo.deleteById(historic.id);
  await request('蓝图项目的材料在哪里');
  ok(!payload.assistantMemory.previousUserMessages.some((m: any) => m.id === historic.id), 'deleted historical evidence is no longer available');
  const employment = (await db.secretaryBindings.get(uid))!;
  await dismissSecretary(uid, character.id, employment.employmentId!);
  await rejects(() => request('记住：离职后不能写入'), 'dismissed assistant cannot capture more memory');
  character = await createSecretary(uid, '明明', { personality: 'professional', expectedRevision: (await db.secretaryBindings.get(uid))!.revision });
  await session(); await request('杭州工作');
  ok(payload.assistantMemory.memories.some((m: any) => m.content.includes('杭州')), 're-hiring retains account information');
  ok(prompt.includes('不冒称当前助理亲历'), 'new employment treats past records as handed-over information');
  await request('记住：我喜欢安静的环境');
  let quiet = (await rows()).find(m => m.content.includes('安静'))!;
  await editSecretaryMemory(uid, character.id, quiet.id, '我喜欢明亮的环境', quiet.updatedAt!);
  ok((await rows()).some(m => m.content === '我喜欢明亮的环境'), 'manual correction becomes the next active memory');
  await rejects(() => editSecretaryMemory(uid, character.id, quiet.id, '过期编辑', quiet.updatedAt!), 'obsolete memory form cannot overwrite a correction');
  quiet = (await rows()).find(m => m.id === quiet.id)!;
  before = () => editSecretaryMemory(uid, character.id, quiet.id, null, quiet.updatedAt!);
  await rejects(() => request('明亮的环境你怎么看'), 'late planner reply is discarded when recalled memory is forgotten meanwhile');
  ok(!(await rows()).some(m => m.id === quiet.id), 'late reply cannot revive the forgotten fact');
  before = async () => { auth('other-owner'); };
  await rejects(() => request('我长期在苏州工作', { reply: '', actions: [], memories: [{ kind: 'fact', quote: '我长期在苏州工作' }] }), 'account switch stops delayed memory capture');
  auth(); ok(!(await rows()).some(m => m.content.includes('苏州')), 'delayed memory was never committed to either account');
  useChatStore.setState({ characters: [character], selectedCharacterId: character.id, currentSessionId: sid });
  root.render(<SecretaryMoreMenu onInbox={() => {}} onReview={() => {}} onManage={() => {}} disabled={false} />);
  await button('助理更多操作'); await button('助理记忆 · 查看、纠正与忘记');
  ok(document.querySelector('[role="dialog"]')?.textContent?.includes('助理记忆'), 'real assistant menu opens the memory manager');
  await button('纠正：我长期在杭州工作');
  const input = document.querySelector('textarea[aria-label="纠正记忆内容"]') as HTMLTextAreaElement;
  Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, 'value')!.set!.call(input, '我长期在南京工作');
  input.dispatchEvent(new Event('input', { bubbles: true })); await wait(); await button('保存纠正');
  ok((await rows()).some(m => m.content === '我长期在南京工作'), 'real React editor commits correction to IndexedDB');
  await button('忘记：我长期在南京工作');
  ok(!(await rows()).some(m => m.content.includes('南京')), 'real forget button removes memory without deleting conversation');
  ok(await db.messages.get(corrected.message.id), 'memory forgetting preserves original conversation for the user');
  root.render(<SecretaryMemoryModal open onClose={() => {}} />); await wait();
  auth('another-owner'); await wait();
  ok(!document.body.textContent?.includes('杭州') && !document.body.textContent?.includes('南京'), 'account switch clears visible memory immediately');
  root.unmount(); auth();
  await request('记住：我喜欢柠檬水');
  await request('忘记全部长期记忆');
  ok((await rows()).length === 0, 'forget all clears all active facts');
  await request('柠檬水、杭州工作、南京工作');
  ok(!JSON.stringify(payload).includes('我喜欢柠檬水') && !JSON.stringify(payload).includes('我长期在杭州工作'), 'forget all also suppresses unstructured old personal statements');
  await request('记住：我喜欢桂花茶');
  ok((await rows()).some(m => m.content.includes('桂花茶')), 'new explicit facts can be learned after forgetting old information');
  db.close(); await db.open();
  ok((await rows()).some(m => m.content.includes('桂花茶')), 'long-term memory survives database close and reopen');
  await request('记住：我在沈阳工作');
  await session(); await request('聊聊电影');
  ok(!payload.assistantMemory.memories.some((m: any) => m.content.includes('沈阳') || m.content.includes('桂花茶')), 'unrelated personal facts no longer occupy casual-chat context');
  await request('桂花茶喝起来怎么样', { reply: '我记得你说过：我喜欢桂花茶。', actions: [] });
  ok(payload.assistantMemory.memories.some((m: any) => m.content.includes('桂花茶')), 'single-subject query retrieves the corresponding preference');
  await request('说个笑话');
  ok(!JSON.stringify(payload.assistantMemory).includes('我喜欢桂花茶'), 'cooled personal subject cannot be revived through raw old evidence');
  await request('茶呢');
  ok(payload.assistantMemory.memories.some((m: any) => m.content.includes('桂花茶')), 'explicit short subject reopens a recently mentioned memory');
  await request('记住：我喜欢简短的回复');
  await request('你好', { reply: '我记得你说：我喜欢简短的回复。', actions: [] });
  ok(payload.assistantMemory.memories.some((m: any) => m.content.includes('简短的回复')), 'persistent expression preference can support a new conversational subject');
  await request('随便聊聊');
  ok(!JSON.stringify(payload.assistantMemory).includes('我喜欢简短的回复'), 'spoken style preference enters cooldown without raw-history duplication');
  await request('回复能简短一点吗');
  ok(payload.assistantMemory.memories.some((m: any) => m.content.includes('简短的回复')), 'direct request for style can reopen cooled expression preference');
  await request('不要再记住沈阳');
  ok(!(await rows()).some(m => m.content.includes('沈阳')), 'do-not-remember-again removes an existing fact rather than merely opting out of extraction');
  await request('沈阳工作你还记得吗');
  ok(!JSON.stringify(payload).includes('我在沈阳工作'), 'negative forget wording suppresses the original source too');
  const travel = await request('新增待办海岛旅行', { reply: '', actions: [{ kind: 'todo.create', title: '海岛旅行' }] });
  const travelId = travel.task.results[0].targetId!;
  await request('海岛旅行待办改为重要', { reply: '', actions: [{ kind: 'todo.update', query: '海岛旅行', priority: 'important' }] });
  await session(); await request('海岛旅行进度怎样');
  ok(payload.assistantMemory.taskProgress.flatMap((t: any) => t.results).filter((r: any) => r.targetId === travelId).length === 1, 'several receipts for the same live task do not duplicate recalled progress');
  before = async () => { await todoRepo.update(uid, travelId, { note: '在回答生成期间更新' }); };
  await rejects(() => request('海岛旅行进度怎样'), 'record edit during generation rejects stale task-progress reply');
  const latestTravel = await request('海岛旅行进度怎样');
  const currentTravel = await db.todos.get(travelId);
  ok(latestTravel.task.memoryReferences?.recordVersions?.some(r => r.kind === 'todo' && r.id === travelId && r.version === currentTravel!.updatedAt), 'task receipt contains the actual current record version');
  // The latest task-progress receipt may cite the update rather than creation; delete that actual source.
  before = async () => {
    const reference = latestTravel.task.memoryReferences?.taskIds[0];
    const origin = reference ? await db.secretaryTasks.get(reference) : undefined;
    if (origin) await db.messages.delete(origin.messageId);
  };
  await rejects(() => request('海岛旅行进度怎样'), 'withdrawn task source during generation is rejected even if the receipt still exists');
  const exercise = await request('新增每天慢跑待办，从今天开始', { reply: '', actions: [{ kind: 'todo.create', title: '每天慢跑', date: localDateKey(), recurrence: 'daily' }] });
  const exerciseId = exercise.task.results[0].targetId!;
  before = () => todoRepo.complete(uid, exerciseId, localDateKey());
  await rejects(() => request('每天慢跑进度怎样'), 'a newly completed occurrence during generation invalidates a previously absent instance snapshot');
  await request('每天慢跑进度怎样');
  ok(payload.assistantMemory.taskProgress.some((t: any) => t.results.some((r: any) => r.targetId === exerciseId && r.currentState === 'completed')), 'fresh recall reflects actual occurrence completion');
  const generationReviewMessage: Message = { id: crypto.randomUUID(), sessionId: sid, role: 'user', content: dailyReviewRequest(reviewOptions), createdAt: Date.now(), isProactive: false };
  next = { reply: '', actions: [{ kind: 'moment.draft', content: 'PRIVATE_DIARY_LATE_DRAFT' }] };
  await messageRepo.create(generationReviewMessage);
  await runSecretaryRequest(uid, character.id, generationReviewMessage, { dailyReview: reviewOptions });
  useSettingsStore.setState({ diaryPin: 'locked' }); setDiaryUnlocked(true);
  before = async () => { setDiaryUnlocked(false); };
  await rejects(() => request('每日整理朋友圈草稿还有哪些'), 'relocking diary during generation blocks a reply derived from its draft');
  useSettingsStore.setState({ diaryPin: null });
  await request('记住：我喜欢桂花茶');
  await report('/result?suite=secretary-memory', { method: 'POST', body: `ok ${checks} assertions\nALL PASS` });
}
run().catch(async e => report('/result?suite=secretary-memory', { method: 'POST', body: `FAIL ${String(e.stack || e)}\n1 FAILED` }));
