import { createRequire } from 'node:module';
import { dirname, join, resolve, extname } from 'node:path';
import { readFileSync, mkdirSync } from 'node:fs';
import { createServer } from 'node:http';

// Checks the isolated design prototype only; never mounts or reads the app DB.
const { chromium } = createRequire(join(dirname(process.execPath), 'package.json'))('playwright');
const root = resolve('.');
const artifacts = join(root, '.tmp-preview/workbench-design');
mkdirSync(artifacts, { recursive: true });
const server = createServer((req, res) => {
  const file = resolve(root, '.' + decodeURIComponent(new URL(req.url, 'http://localhost').pathname));
  if (!file.startsWith(root + '\\') && !file.startsWith(root + '/')) { res.writeHead(403); res.end(); return; }
  try {
    const mime = { '.html': 'text/html; charset=utf-8', '.css': 'text/css; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.woff2': 'font/woff2', '.webp': 'image/webp' };
    res.setHeader('Content-Type', mime[extname(file)] || 'application/octet-stream');
    res.end(readFileSync(file));
  } catch { res.writeHead(404); res.end(); }
});
await new Promise(r => server.listen(0, '127.0.0.1', r));
const url = `http://127.0.0.1:${server.address().port}/docs/prototypes/workbench.html`;
const browser = await chromium.launch({ channel: 'chrome', headless: true });
let checks = 0;
const check = (ok, label) => { if (!ok) throw new Error(label); checks++; console.log('ok ' + label); };
try {
  const context = await browser.newContext({ viewport: { width: 1400, height: 1060 }, reducedMotion: 'reduce', permissions: ['clipboard-read', 'clipboard-write'] });
  const page = await context.newPage();
  const errors = []; const failed = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('response', r => { if (r.status() >= 400 && !r.url().endsWith('favicon.ico')) failed.push(r.url()); });
  await page.goto(url); await page.evaluate(() => document.fonts.ready);
  const snapshot = name => page.screenshot({ path: join(artifacts, name + '.png') });
  const navigate = name => page.locator(`.tabs [data-nav="${name}"]`).click();
  const read = expression => page.evaluate(expression);
  const state = () => read(() => JSON.parse(localStorage.getItem('virtugene:workbench-design:v1')));
  const reset = async () => { await page.evaluate(() => { localStorage.clear(); }); await page.reload(); };
  const editProject = async id => {
    await navigate('projects'); await page.locator('[data-project-filter="all"]').click();
    await page.locator(`[data-action="project"][data-id="${id}"]`).click();
    await page.locator('[data-action="edit-project"]').click();
  };
  const closeProject = async (id, resolution, target) => {
    await editProject(id); await page.locator('#project-form [name="state"]').selectOption('completed');
    await page.locator('#project-form button[type="submit"]').click();
    await page.locator(`[name="resolution"][value="${resolution}"]`).check();
    if (target) await page.locator('#finish-project-form [name="target"]').selectOption(target);
    await page.locator('#finish-project-form button[type="submit"]').click();
  };
  await snapshot('overview');
  check(await page.locator('.focus-row .task-title').allTextContents().then(t => t.join('|') === '确认发布方案的最终版本|提交产品演示材料|整理会议后的需求清单'), 'top three follow deadline and priority');
  check(await page.locator('.demo-chip').textContent() === '示例数据', 'demo data is always labelled');
  await page.setViewportSize({ width: 390, height: 844 });
  const panels = [];
  for (const name of ['today', 'projects', 'inbox', 'risks', 'week']) {
    await navigate(name); await snapshot(name);
    panels.push((await page.screenshot()).toString('base64'));
  }
  const gallery = await context.newPage();
  await gallery.setViewportSize({ width: 1500, height: 910 });
  await gallery.setContent(`<html lang="zh-CN"><head><style>body{margin:0;background:#efedf6;color:#252339;font-family:'Microsoft YaHei',sans-serif;padding:34px 34px 25px;box-sizing:border-box}header{display:flex;justify-content:space-between;align-items:end;margin-bottom:24px}h1{font-size:27px;letter-spacing:-.6px;font-weight:600;margin:0}p{font-size:12px;color:#817e91;margin:8px 0 0}small{font-size:12px;color:#817e91}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:20px}.panel{min-width:0}h2{font-size:13px;font-weight:500;margin:0 0 11px;color:#6c5ce7}img{width:100%;border:5px solid #fff;border-radius:23px;box-shadow:0 14px 30px #3424510a;box-sizing:border-box}.caption{font-size:12px;line-height:1.8;color:#817e91;margin-top:12px}</style></head><body><header><div><h1>VirtuGene · 行动舱</h1><p>把碎片交代、项目进度与待跟进反馈，整理成每天能用的工作空间。</p></div><small>设计提案 06 · 示例数据</small></header><div class="grid">${[['01 今日重点','首屏压紧，数字可直达分组，安排少填表。'],['02 项目中心','支持搜索，收尾前明确处理剩余任务。'],['03 任务收集','一段交代可拆成多项，日期不明确就留空。'],['04 风险雷达','每项标明类型和依据，点开直接调整安排。'],['05 本周复盘','切换周次，完成记录和编辑草稿都能保留。']].map(([label,caption],i)=>`<div class="panel"><h2>${label}</h2><img src="data:image/png;base64,${panels[i]}"><div class="caption">${caption}</div></div>`).join('')}</div><p style="margin-top:27px">生活助理 → 打开行动舱　　｜　　交互设计原型，使用独立的本地示例数据，尚未接入正式应用。</p></body></html>`);
  await gallery.screenshot({ path: join(artifacts, 'five-pages.png'), fullPage: true });
  await gallery.close();
  await navigate('today');
  check((await page.locator('#page-heading').innerText()).startsWith('行动舱') && await page.locator('.composer img').count() === 0 && await page.locator('.quick-note-icon svg').count() === 1, 'action cabin name and manual note icon are consistent');
  check((await page.locator('.carry-focus-notice').innerText()).includes('昨天还有 1 件重点没完成') && await read(() => data.tasks.find(t => t.id === 't11').focusDate === '2026-10-02'), 'yesterday focus is surfaced without automatic rollover');
  await page.locator('[data-action="carry-focus"]').click();
  await page.locator('#carry-focus-form [data-action="close"]').click();
  check(await read(() => data.tasks.find(t => t.id === 't11').focusDate === '2026-10-02'), 'dismissed carry confirmation leaves original focus date intact');
  await page.evaluate(() => { for (const id of ['t4','t5','t7']) data.tasks.find(t => t.id === id).focusDate = '2026-10-02'; save(); render(false); });
  check((await page.locator('.carry-focus-notice').innerText()).includes('昨天还有 3 件重点没完成'), 'yesterday notice excludes already completed focus');
  await page.locator('[data-action="carry-focus"]').click();
  await page.locator('#carry-focus-form [value="t5"]').uncheck();
  await page.locator('#carry-focus-form button[type="submit"]').click();
  check((await state()).tasks.filter(t => ['t4','t11'].includes(t.id)).every(t => t.focusDate === '2026-10-03') && (await state()).tasks.find(t => t.id === 't5').focusDate === '2026-10-02', 'carry confirmation modifies only selected incomplete focus');
  check((await state()).tasks.find(t => t.id === 't4').status === 'waiting' && (await state()).tasks.find(t => t.id === 't11').due === '2026-10-08' && !(await page.locator('.focus').innerText()).includes('跟进客户的预算确认'), 'carry leaves deadline and waiting state unchanged and respects priority ranking');
  await page.locator('[data-action="undo"]').click();
  check((await state()).tasks.find(t => t.id === 't11').focusDate === '2026-10-02' && (await page.locator('.carry-focus-notice').innerText()).includes('3 件'), 'carry undo restores all prior focus dates and notice');
  await page.locator('[data-action="carry-focus"]').click();
  for (const input of await page.locator('#carry-focus-form input').all()) await input.uncheck();
  await page.locator('#carry-focus-form button[type="submit"]').click();
  check(await page.locator('#carry-focus-form').isVisible() && (await state()).tasks.find(t => t.id === 't11').focusDate === '2026-10-02', 'empty carry selection never writes or dismisses the form');
  await page.locator('#carry-focus-form [value="t11"]').check();
  await page.evaluate(() => { window.originalStorageSet = Storage.prototype.setItem; Storage.prototype.setItem = function(k,v) { if (k === 'virtugene:workbench-design:v1') throw new DOMException('Quota exceeded','QuotaExceededError'); return window.originalStorageSet.call(this,k,v); }; });
  await page.locator('#carry-focus-form button[type="submit"]').click();
  check(await page.locator('#carry-focus-form').isVisible() && await page.locator('#carry-focus-form [value="t11"]').isChecked() && (await state()).tasks.find(t => t.id === 't11').focusDate === '2026-10-02', 'failed carry save rolls back and retains selected input for retry');
  await page.evaluate(() => { Storage.prototype.setItem = window.originalStorageSet; });
  await page.locator('#carry-focus-form button[type="submit"]').click();
  check((await state()).tasks.find(t => t.id === 't11').focusDate === '2026-10-03' && await page.locator('#carry-focus-form').count() === 0, 'same carry form succeeds after storage recovers');
  await reset();
  await page.evaluate(() => {
    for (let i = 0; i < 205; i++) data.tasks.push({id:'page-'+i,title:'分页事项 '+i,due:'2026-10-12',priority:'normal',status:'todo'});
    data.tasks.find(t => t.id === 'page-10').time = '18:00';
    data.tasks.find(t => t.id === 'page-20').time = '09:00';
    save(); render(false);
  });
  await page.locator('[data-action="task-center"]').click();
  check(await page.locator('.task-center-row').count() === 100, 'task center initially renders a bounded batch');
  await page.locator('[data-action="toggle-selection"]').click();
  await page.locator('[data-action="select-visible"]').click();
  await page.locator('[data-action="load-more-tasks"]').click();
  check(await page.locator('.task-center-row').count() === 200 && (await page.locator('.batch-toolbar').innerText()).includes('已选 100 项'), 'load more retains original selection and exposes second batch');
  await page.locator('[data-action="select-visible"]').click();
  check((await page.locator('.batch-toolbar').innerText()).includes('已选 200 项'), 'select visible includes newly loaded rows');
  await page.locator('[data-action="load-more-tasks"]').click();
  check(await page.locator('.task-center-row').count() === 212 && await page.locator('[data-action="load-more-tasks"]').count() === 0 && (await page.locator('#task-center-results [role="status"]').innerText()).includes('212 / 212'), 'last batch includes every matching task without truncation');
  const orderedTitles = await page.locator('.task-center-row .task-title').allTextContents();
  check(orderedTitles.indexOf('分页事项 20') < orderedTitles.indexOf('分页事项 10'), 'same-day task list orders real deadline times before stable IDs');
  await page.locator('#task-search').fill('分页事项 204');
  check(await page.locator('.task-center-row').count() === 1 && (await page.locator('.batch-toolbar').innerText()).includes('已选 0 项'), 'search finds final row and clears previous selection');
  await page.locator('[data-action="clear-task-search"]').click();
  check(await page.locator('.task-center-row').count() === 100, 'cleared query restarts bounded rendering');
  await page.locator('[data-action="load-more-tasks"]').click();
  const editingRow = page.locator('.task-center [data-action="edit"]').nth(75), editingId = await editingRow.getAttribute('data-id');
  await editingRow.click();
  const rememberedScroll = await read(() => centerScroll);
  check(rememberedScroll > 0, 'opening a deep task records the actual scrolled position');
  await page.locator('#task-form .extra-fields summary').click();
  await page.locator('#task-form [name="note"]').fill('保留列表位置的编辑');
  await page.locator('#task-form button[type="submit"]').click();
  check(await page.locator('.task-center-row').count() === 200 && await read(() => Math.abs(document.getElementById('task-center-results').scrollTop - centerScroll) < 2), 'saved edit returns to loaded rows and previous scroll position');
  check(await read(() => document.activeElement.dataset.id) === editingId && (await state()).tasks.find(t => t.id === editingId).note === '保留列表位置的编辑', 'saved edit returns keyboard focus to the original task');
  await page.locator(`.task-center [data-action="edit"][data-id="${editingId}"]`).click();
  await page.locator('#task-form [name="title"]').fill('未保存的标题');
  await page.keyboard.press('Escape');
  check(await page.getByRole('dialog',{name:'全部任务'}).isVisible() && (await state()).tasks.find(t => t.id === editingId).title !== '未保存的标题' && await read(() => Math.abs(document.getElementById('task-center-results').scrollTop - centerScroll) < 2), 'dismissed editor returns to the same list without persisting abandoned input');
  const selectingRow = page.locator(`[data-select-task="${editingId}"]`);
  await selectingRow.scrollIntoViewIfNeeded();
  const beforeSelection = await page.locator('#task-center-results').evaluate(el => el.scrollTop);
  await selectingRow.check();
  check(await page.locator('#task-center-results').evaluate((el,before) => Math.abs(el.scrollTop-before)<2,beforeSelection), 'selection refresh does not jump the scrolled list');
  await reset();
  await page.locator('[data-action="task-center"]').click();
  await page.locator('.task-center [data-action="edit"][data-id="t11"]').click();
  await page.locator('#task-form [name="title"]').fill('和行政确认流程负责人（补充）');
  await page.locator('#task-form button[type="submit"]').click();
  check((await state()).tasks.find(t => t.id === 't11').focusDate === '2026-10-02', 'ordinary editing preserves expired focus rather than erasing yesterday notice');
  await page.keyboard.press('Escape');
  check((await page.locator('.carry-focus-notice').innerText()).includes('昨天还有 1 件重点没完成'), 'yesterday reminder remains available after an ordinary edit');
  await page.locator('[data-action="task-center"]').click();
  await page.locator('.task-center [data-action="edit"][data-id="t6"]').click();
  await page.locator('#task-form [name="focus"]').uncheck();
  await page.locator('#task-form button[type="submit"]').click();
  check((await state()).tasks.find(t => t.id === 't6').focusDate === '', 'explicitly unchecking current focus still clears it');
  await reset(); await navigate('risks'); await page.locator('[data-risk-filter="waiting"]').click();
  await page.locator('[data-action="quick-followup"][data-task-id="t4"]').click();
  check(await page.getByRole('dialog',{name:'安排下一次跟进'}).isVisible() && (await state()) === null, 'quick followup opens a focused form without changing data');
  await snapshot('quick-followup');
  await page.locator('[data-followup-date="2026-10-03"]').click();
  await page.locator('#followup-form button[type="submit"]').click();
  check(await page.locator('.risk-card').count() === 1 && (await state()).tasks.find(t => t.id === 't4').followup === '2026-10-03', 'same-day followup retains actionable reminder');
  await page.locator('[data-action="quick-followup"][data-task-id="t4"]').click();
  await page.locator('[data-followup-date="2026-10-06"]').click();
  await page.locator('#followup-form [name="waitingFor"]').fill('客户采购负责人');
  await page.evaluate(() => { window.originalStorageSet = Storage.prototype.setItem; Storage.prototype.setItem = function(k,v) { if (k === 'virtugene:workbench-design:v1') throw new DOMException('Quota exceeded','QuotaExceededError'); return window.originalStorageSet.call(this,k,v); }; });
  await page.locator('#followup-form button[type="submit"]').click();
  check(await page.locator('#followup-form').isVisible() && await page.locator('#followup-form [name="waitingFor"]').inputValue() === '客户采购负责人' && (await state()).tasks.find(t => t.id === 't4').followup === '2026-10-03', 'failed quick followup preserves input and rolls back scheduling');
  await page.evaluate(() => { Storage.prototype.setItem = window.originalStorageSet; });
  await page.locator('#followup-form button[type="submit"]').click();
  const followed = (await state()).tasks.find(t => t.id === 't4');
  check(await page.locator('.risk-card').count() === 0 && followed.followup === '2026-10-06' && followed.waitingFor === '客户采购负责人' && followed.waitingSince === '2026-09-29' && followed.status === 'waiting' && followed.due === '2026-10-07', 'future followup clears reminder without changing deadline or pretending contact');
  await page.locator('[data-action="undo"]').click();
  check(await page.locator('.risk-card').count() === 1 && (await state()).tasks.find(t => t.id === 't4').waitingFor === '客户采购同事', 'followup undo restores previous arrangement and risk');
  await reset();
  for (const width of [320, 390, 430]) {
    await page.setViewportSize({ width, height: 844 });
    for (const name of ['today', 'projects', 'inbox', 'risks', 'week']) {
      await navigate(name);
      check(await read(() => document.documentElement.scrollWidth <= innerWidth && document.querySelector('.scroll').scrollWidth <= document.querySelector('.scroll').clientWidth), `${name} fits ${width}px`);
    }
  }
  await page.setViewportSize({ width: 390, height: 844 }); await navigate('today');
  await page.locator('.focus [data-action="complete"][data-id="t1"]').click();
  check((await state()).tasks.find(t => t.id === 't1').completedAt === '2026-10-03', 'complete saves completion time');
  check(await page.locator('.stat strong.red').textContent() === '0', 'completing overdue task updates dashboard');
  await page.locator('[data-action="undo"]').click();
  check((await state()).tasks.find(t => t.id === 't1').status === 'doing' && !(await state()).tasks.find(t => t.id === 't1').completedAt, 'undo restores state and removes completion timestamp');
  await page.locator('.focus [data-action="edit"][data-id="t2"]').click();
  await snapshot('task-edit');
  await page.keyboard.press('Shift+Tab');
  check(await read(() => document.querySelector('.sheet').contains(document.activeElement)), 'keyboard focus stays inside task sheet');
  await page.locator('#task-form [name="due"]').fill('2026-10-10');
  await page.locator('#task-form [name="status"]').selectOption('waiting');
  await page.locator('#task-form [name="waitingFor"]').fill('设计同事');
  await page.locator('#task-form [name="followup"]').fill('2026-10-09');
  await page.locator('#task-form button[type="submit"]').click();
  check((await state()).tasks.find(t => t.id === 't2').waitingSince === '2026-10-03', 'editing task status starts waiting interval');
  check(!(await page.locator('.focus').innerText()).includes('提交产品演示材料'), 'waiting tasks leave actionable priorities');
  await page.reload();
  check((await state()).tasks.find(t => t.id === 't2').waitingFor === '设计同事', 'demo edits survive reload');
  await navigate('risks');
  await page.locator('[data-risk-filter="waiting"]').click();
  check(await page.locator('.risk-card').count() === 1, 'waiting radar filters only followups due');
  await page.locator('.risk-card [data-id="t4"]').click();
  await page.locator('#task-form [name="followup"]').fill('2026-10-10');
  await page.locator('#task-form button[type="submit"]').click();
  check(await page.locator('.risk-card').count() === 0, 'future followup suppresses age-based waiting alert');
  await reset(); await navigate('projects');
  await page.locator('[data-action="project"][data-id="p1"]').click();
  await snapshot('project-detail');
  check((await page.locator('.sheet .project-meta').innerText()).includes('40%'), 'project progress comes from associated tasks');
  await page.keyboard.press('Escape');
  await page.locator('[data-action="new-project"]').click();
  await page.locator('#project-form [name="name"]').fill('试用项目');
  await page.locator('#project-form [name="due"]').fill('2026-10-01');
  await page.locator('#project-form button[type="submit"]').click();
  check(await page.locator('#project-form').count() === 1 && (await page.locator('#toast').innerText()).includes('不能早于'), 'invalid project date is rejected without losing form');
  await page.locator('#project-form [name="due"]').fill('2026-10-09');
  await page.locator('#project-form [name="next"]').fill('安排需求评审');
  await page.locator('#project-form button[type="submit"]').click();
  check((await state()).projects.length === 4, 'new project is saved');
  await page.locator('[data-action="project"][data-id="p3"]').click();
  await page.locator('[data-action="edit-project"]').click();
  await page.locator('#project-form [name="state"]').selectOption('completed');
  await page.locator('#project-form button[type="submit"]').click();
  check(await page.locator('#finish-project-form').count() === 1 && !(await state()).projects.find(p => p.id === 'p3').completed, 'closing project reviews remaining tasks before mutation');
  await snapshot('project-finish');
  await page.locator('#finish-project-form button[type="submit"]').click();
  await page.locator('[data-project-filter="done"]').click();
  check(await page.locator('.project').count() === 1 && (await page.locator('.project').innerText()).includes('内部流程整理'), 'project completion is explicit and filterable');
  check((await state()).tasks.filter(t => ['t6','t11'].includes(t.id)).every(t => t.project === '' && t.status === 'todo'), 'project closure keeps unresolved work actionable as independent tasks');
  await reset(); await navigate('inbox');
  await page.locator('[data-action="triage"][data-id="i1"]').click();
  await page.locator('#task-form [name="title"]').fill('补充客户案例');
  await page.locator('#task-form [name="project"]').selectOption('p1');
  await page.locator('#task-form [name="due"]').fill('2026-10-05');
  await page.locator('#task-form button[type="submit"]').click();
  check((await state()).captures.length === 2 && (await state()).tasks.find(t => t.title === '补充客户案例').sourceText.includes('领导说'), 'triage preserves raw source and removes only converted capture');
  await page.locator('[data-action="undo"]').click();
  check((await state()).captures.length === 3 && (await state()).tasks.length === 11, 'triage undo restores both sides');
  await page.locator('#capture').click();
  await page.locator('#capture-form [name="text"]').fill('会议后更新项目安排');
  await page.locator('#capture-form button[type="submit"]').click();
  check((await state()).captures.length === 4, 'quick capture creates an inbox item');
  await navigate('today'); await page.locator('#add').click();
  await page.locator('#task-form [name="title"]').fill('临时事项');
  await page.locator('#task-form [name="due"]').fill('2026-10-03');
  await page.locator('#task-form [name="priority"]').selectOption('urgent');
  await page.locator('#task-form button[type="submit"]').click();
  const added = (await state()).tasks.find(t => t.title === '临时事项');
  check(!!added && (await page.locator('.focus').innerText()).includes('临时事项'), 'new urgent task enters priorities');
  await page.locator(`.focus [data-action="edit"][data-id="${added.id}"]`).click();
  await page.locator('[data-action="delete"]').click();
  await page.locator('[data-action="confirm-delete"]').click();
  check(!(await state()).tasks.some(t => t.id === added.id), 'delete removes selected demo task');
  await page.locator('[data-action="undo"]').click();
  check((await state()).tasks.some(t => t.id === added.id), 'delete undo restores selected task');
  await navigate('week'); await page.locator('[data-action="review"]').click();
  const draft = await page.locator('#review-text').inputValue();
  check(draft.includes('发送发布会议纪要') && draft.includes('下周已有安排') && !draft.split('项目当前状态')[0].includes('临时事项'), 'weekly draft separates real completion from upcoming work');
  await page.locator('#review-text').fill(draft + '\n补充：下周先跟进客户反馈。');
  await page.locator('[data-action="copy-review"]').click();
  await page.waitForFunction(() => document.getElementById('toast').textContent.includes('已复制'));
  check((await read(() => navigator.clipboard.readText())).endsWith('下周先跟进客户反馈。'), 'weekly copy uses edited draft');
  await page.keyboard.press('Escape');
  check(await page.locator('.sheet').count() === 0, 'escape closes sheet');
  check(await read(() => matchMedia('(prefers-reduced-motion: reduce)').matches && getComputedStyle(document.querySelector('.page-enter')).animationName === 'none'), 'reduced motion disables transitions');
  await page.locator('#back').click(); await snapshot('assistant-entry');
  check(await page.locator('.tabs').isHidden() && await page.locator('[data-action="open-workbench"]').isVisible(), 'assistant entry has separate chat and workspace actions');
  await page.locator('[data-action="open-workbench"]').click();
  check(await page.locator('#tab-week').getAttribute('aria-selected') === 'true', 'entry round trip preserves selected page');
  await page.locator('#tab-week').focus(); await page.keyboard.press('Home'); await page.keyboard.press('ArrowRight');
  check(await page.locator('#tab-projects').getAttribute('aria-selected') === 'true' && await read(() => document.activeElement.id === 'tab-projects'), 'arrow keys and home navigate accessible tabs');
  await page.locator('#project-search').fill('预算确认');
  check(await page.locator('.project').count() === 1 && (await page.locator('.project').innerText()).includes('客户方案交付'), 'project search includes next action');
  await page.locator('#project-search').fill('不存在的名称');
  check(await page.locator('.project').count() === 0 && (await page.locator('#project-results').innerText()).includes('没有匹配'), 'search empty result has guidance');
  await page.locator('[data-action="clear-search"]').click();
  check(await page.locator('.project').count() === 3, 'clear search restores filtered projects');
  await reset(); await navigate('today'); await page.locator('#add').click();
  check(await page.locator('#waiting-fields').isHidden() && !(await page.locator('.extra-fields').getAttribute('open')), 'ordinary task keeps waiting fields and notes folded');
  await page.locator('[data-date="2026-10-04"]').click();
  check(await page.locator('[name="due"]').inputValue() === '2026-10-04', 'tomorrow shortcut sets the calendar date');
  await page.locator('[name="time"]').fill('16:00'); await page.locator('[data-date=""]').click();
  check(await page.locator('[name="due"]').inputValue() === '' && await page.locator('[name="time"]').inputValue() === '', 'unscheduled shortcut clears date and orphan time');
  await page.locator('[name="status"]').selectOption('waiting');
  check(await page.locator('#waiting-fields').isVisible(), 'waiting status reveals only relevant fields');
  await page.locator('[name="status"]').selectOption('blocked');
  check(await page.locator('.extra-fields').getAttribute('open') !== null && await page.locator('#waiting-fields').isHidden(), 'blocked status opens reason and hides waiting fields');
  check(await read(() => document.getElementById('content').inert && document.querySelector('.tabs').inert), 'sheet makes background content inert');
  await page.keyboard.press('Escape');
  check(await read(() => !document.getElementById('content').inert), 'closing sheet restores background interaction');
  await navigate('inbox'); await page.locator('[data-action="triage"][data-id="i2"]').click();
  await page.locator('[data-action="split-capture"]').click();
  await page.locator('#split-form [name="titles"]').fill('整理项目阻塞清单\n确认各项跟进人');
  await snapshot('split-capture');
  check((await page.locator('#split-preview').innerText()).includes('准备加入 2 项'), 'split preview shows exact pending tasks');
  await page.locator('#split-form button[type="submit"]').click();
  const split = (await state()).tasks.filter(t => t.sourceText?.includes('各项目当前阻塞点'));
  check(split.length === 2 && split.every(t => !t.due && !t.project && t.source === '会后速记'), 'split preserves each source without inventing date or project');
  await page.locator('[data-action="undo"]').click();
  check((await state()).tasks.length === 11 && (await state()).captures.some(i => i.id === 'i2'), 'split undo restores source and removes all generated candidates');
  await reset(); await closeProject('p3','move','p1');
  check((await state()).tasks.filter(t => ['t6','t11'].includes(t.id)).every(t => t.project === 'p1' && t.status === 'todo'), 'project closure migration preserves task states');
  await page.locator('[data-action="undo"]').click();
  check(!(await state()).projects.find(p => p.id === 'p3').completed && (await state()).tasks.find(t => t.id === 't6').project === 'p3', 'project closure undo restores lifecycle and ownership');
  await closeProject('p3','cancel');
  check((await state()).tasks.filter(t => ['t6','t11'].includes(t.id)).every(t => t.status === 'cancelled') && (await state()).events.length === 4, 'cancelled work is preserved without becoming completed events');
  await navigate('risks');
  check(!(await page.locator('#content').innerText()).includes('补齐新人入职清单'), 'cancelled task leaves risk radar');
  await navigate('projects'); await page.locator('[data-project-filter="done"]').click();
  await page.locator('[data-action="project"][data-id="p3"]').click();
  check((await page.locator('.sheet .project-meta').innerText()).includes('100%'), 'cancelled tasks do not inflate progress denominator');
  await page.locator('.cancelled-records summary').click();
  check((await page.locator('.cancelled-records').innerText()).includes('补齐新人入职清单'), 'cancelled project tasks remain inspectable');
  await page.locator('.sheet [data-action="complete"][data-id="t10"]').click();
  check(await page.getByRole('dialog', { name: '重新打开任务' }).count() === 1, 'restoring task in closed project explains project reopening');
  await page.locator('[data-action="restore-project-task"]').click();
  check(!(await state()).projects.find(p => p.id === 'p3').completed && (await state()).tasks.find(t => t.id === 't10').status === 'todo' && (await state()).events.length === 4, 'restoring closed project task preserves history and reopens both');
  await reset(); await navigate('projects'); await page.locator('[data-action="new-project"]').click();
  await page.locator('[name="name"]').fill('尚未拆任务的项目'); await page.locator('#project-form button[type="submit"]').click();
  check((await page.locator('.project').last().innerText()).includes('暂无进度') && !(await page.locator('.project').last().innerText()).includes('0%'), 'project without tasks avoids misleading progress');
  await reset(); await navigate('today');
  await page.locator('.focus [data-action="complete"][data-id="t1"]').click();
  await page.locator('[data-task-filter="done"]').click();
  await page.locator('.task-row [data-action="complete"][data-id="t1"]').click();
  await navigate('week');
  check((await page.locator('#content').innerText()).includes('确认发布方案的最终版本') && (await page.locator('#content').innerText()).includes('当前已重新打开'), 'reopening task preserves historical completion with truthful current state');
  await page.locator('[data-action="previous-week"]').click();
  check((await page.locator('.week-controls').innerText()).includes('9 月 21 日—9 月 27 日') && (await page.locator('#content').innerText()).includes('这一周没有完成记录'), 'previous week uses bounded real record dates and useful empty state');
  await page.locator('[data-action="next-week"]').click();
  check(await page.locator('[data-action="next-week"]').isDisabled(), 'week navigation stops at current week');
  await page.locator('[data-action="review"]').click(); await page.locator('#review-text').fill('我自己的复盘结论');
  await page.keyboard.press('Escape'); await page.reload(); await navigate('week'); await page.locator('[data-action="review"]').click();
  check(await page.locator('#review-text').inputValue() === '我自己的复盘结论', 'review edits survive close and reload');
  await page.keyboard.press('Escape'); await navigate('today');
  await page.locator('.focus [data-action="complete"][data-id="t1"]').click();
  await navigate('week'); await page.locator('[data-action="review"]').click();
  check(await page.locator('#review-text').inputValue() === '我自己的复盘结论' && (await page.locator('.sheet-desc').innerText()).includes('记录已有变化'), 'new records flag stale draft without overwriting edits');
  await snapshot('review-draft');
  await page.locator('[data-action="regenerate-review"]').click();
  check(await page.getByRole('dialog',{name:'重新生成复盘'}).count() === 1, 'regeneration warns before replacing manual edits');
  await page.locator('.sheet [data-action="review"]').click();
  check(await page.locator('#review-text').inputValue() === '我自己的复盘结论', 'keeping edited draft leaves manual text intact');
  await page.locator('[data-action="regenerate-review"]').click(); await page.locator('[data-action="confirm-regenerate"]').click();
  check((await page.locator('#review-text').inputValue()).includes('发送发布会议纪要'), 'confirmed regeneration uses current source records');
  await page.keyboard.press('Escape');
  await page.locator('#back').click();
  await page.locator('.demo-actions [data-action="blank-demo"]').click(); await snapshot('empty-state');
  check(await page.locator('.focus-row').count() === 0 && (await page.locator('.focus').innerText()).includes('暂无可推进'), 'blank workbench gives an actionable start');
  await navigate('projects');
  check(await page.locator('[data-action="new-project"]').count() === 2, 'empty projects offer an explicit creation action');
  for (const width of [320,390,430]) {
    await page.setViewportSize({width,height:740}); await navigate('today'); await page.locator('#add').click();
    check(await page.locator('.sheet').evaluate(el => el.scrollWidth <= el.clientWidth && el.getBoundingClientRect().bottom <= innerHeight + 1), `task sheet fits ${width}px and short screen`);
    await page.keyboard.press('Escape');
  }
  await reset(); await page.setViewportSize({width:390,height:844});
  check(await read(() => document.documentElement.dataset.theme) === 'dark', 'default theme follows application dark palette');
  await page.locator('[data-action="task-center"]').click();
  check(await page.locator('.task-center-row').count() === 7, 'all task view exposes pending work beyond today');
  await page.locator('[data-action="new-center-task"]').click();
  await page.locator('[name="title"]').fill('未排期的资料整理'); await page.locator('#task-form button[type="submit"]').click();
  check(await page.locator('.task-center').isVisible() && (await state()).tasks.length === 12, 'new task returns to task center after save');
  await page.locator('[data-center-status="unscheduled"]').click();
  check(await page.locator('.task-center-row').count() === 1 && (await page.locator('.task-center-row').innerText()).includes('未排期'), 'unscheduled view finds tasks without dates');
  await page.locator('[data-center-status="active"]').click();
  await page.locator('#task-search').fill('客户采购同事');
  check(await page.locator('.task-center-row').count() === 1 && (await page.locator('.task-center-row').innerText()).includes('预算确认'), 'task search includes waiting person');
  await page.locator('[data-action="clear-task-search"]').click();
  await page.locator('#task-project').selectOption('p3');
  check(await page.locator('.task-center-row').count() === 2, 'task project filter excludes other ownership');
  await page.locator('#task-project').selectOption('all');
  await page.locator('[data-action="toggle-selection"]').click();
  const selectPair = async () => { for (const id of ['t2','t3']) await page.locator(`[data-select-task="${id}"]`).check(); };
  await selectPair();
  check((await page.locator('.batch-toolbar').innerText()).includes('已选 2 项'), 'batch action count matches explicit selected tasks');
  check(await page.locator('[data-action="batch-complete"]').evaluate(el => el.getBoundingClientRect().bottom <= innerHeight), 'batch toolbar remains visible without scrolling to end of task list');
  await snapshot('task-center');
  const centerImage = (await page.screenshot()).toString('base64');
  await page.locator('[data-action="batch-date"]').click(); await page.locator('#batch-date-form [name="due"]').fill('2026-10-07');
  await page.locator('#batch-date-form button[type="submit"]').click();
  check((await state()).tasks.filter(t => ['t2','t3'].includes(t.id)).every(t => t.due === '2026-10-07') && (await state()).tasks.find(t => t.id === 't2').time === '16:00' && (await state()).tasks.find(t => t.id === 't1').due === '2026-10-02', 'batch date affects only selection and keeps deadline times');
  await page.locator('[data-action="undo"]').click();
  check((await state()).tasks.filter(t => ['t2','t3'].includes(t.id)).every(t => t.due === '2026-10-03'), 'batch date undo restores every original date');
  await selectPair(); await page.locator('[data-action="batch-focus"]').click();
  check((await state()).tasks.filter(t => ['t2','t3'].includes(t.id)).every(t => t.focusDate === '2026-10-03'), 'bulk focus uses an expiring calendar date');
  await selectPair(); await page.locator('[data-action="batch-complete"]').click();
  check((await state()).tasks.filter(t => ['t2','t3'].includes(t.id)).every(t => t.status === 'completed') && (await state()).events.length === 6, 'bulk completion creates exactly one completion event for each task');
  await page.locator('[data-action="undo"]').click();
  check((await state()).events.length === 4 && (await state()).tasks.find(t => t.id === 't2').status === 'todo', 'bulk completion undo restores lifecycle and history atomically');
  await selectPair(); await page.locator('[data-action="batch-cancel"]').click();
  check(await page.getByRole('dialog',{name:'取消所选任务'}).count() === 1 && (await state()).tasks.find(t => t.id === 't2').status === 'todo', 'bulk cancellation previews tasks before mutation');
  await page.locator('[data-action="confirm-batch-cancel"]').click();
  check((await state()).tasks.filter(t => ['t2','t3'].includes(t.id)).every(t => t.status === 'cancelled') && (await state()).events.length === 4, 'bulk cancellation never fabricates completion');
  await page.locator('[data-action="undo"]').click(); await selectPair(); await page.locator('#task-search').fill('资料整理');
  check((await page.locator('.batch-toolbar').innerText()).includes('已选 0 项'), 'changing search clears hidden selections');
  await page.keyboard.press('Escape'); await navigate('today');
  await page.locator('#toast').evaluate(el => { el.innerHTML = ''; });
  const darkImage = (await page.screenshot()).toString('base64');
  await page.locator('#back').click(); await page.locator('.theme-actions [data-action="toggle-theme"]').click(); await page.locator('[data-action="open-workbench"]').click();
  check(await read(() => document.documentElement.dataset.theme) === 'light', 'light theme uses same components and interactions');
  await snapshot('today-light'); const lightImage = (await page.screenshot()).toString('base64');
  const comparison = await context.newPage(); await comparison.setViewportSize({width:1250,height:1000});
  await comparison.setContent(`<html><head><style>body{margin:0;padding:32px;background:#0c1020;color:#eeefff;font-family:'Microsoft YaHei',sans-serif}h1{font-size:26px;font-weight:500;margin:0 0 8px}p{font-size:12px;color:#a6afc9;margin:0 0 24px}.row{display:grid;grid-template-columns:repeat(3,1fr);gap:30px;max-width:1070px;margin:auto}h2{font-size:13px;font-weight:400;color:#ad9bff;margin:0 0 12px}img{width:100%;border-radius:24px;border:5px solid #1d263b;box-sizing:border-box}footer{font-size:12px;color:#a6afc9;line-height:1.9;margin:25px 0}</style></head><body><h1>VirtuGene · 行动舱设计 06</h1><p>沿用应用的紫色、青色、冷白与深蓝表面，保留轻轨道纹理。任务、风险、项目共享记录。</p><div class="row">${[['深色主题 · 与应用默认一致',darkImage],['浅色主题 · 同一套交互',lightImage],['全部任务 · 搜索、筛选与批量安排',centerImage]].map(([l,img])=>`<div><h2>${l}</h2><img src="data:image/png;base64,${img}"></div>`).join('')}</div><footer>设计原型 · 独立示例数据　｜　保存失败回退、原始数据保护、备份恢复校验、多窗口修改检测。</footer></body></html>`);
  await comparison.screenshot({path:join(artifacts,'theme-comparison.png'),fullPage:true}); await comparison.close();
  await page.reload();
  check(await read(() => document.documentElement.dataset.theme) === 'light', 'theme survives reload without resetting tasks');
  for (const width of [320,390,430]) {
    await page.setViewportSize({width,height:844});
    for (const name of ['today','projects','inbox','risks','week']) { await navigate(name); check(await read(() => document.documentElement.scrollWidth <= innerWidth), `light ${name} fits ${width}px`); }
  }
  await page.setViewportSize({width:390,height:844}); await page.locator('#back').click();
  await page.locator('#demo-time').fill('16:01'); await page.locator('#demo-time').dispatchEvent('change');
  await page.locator('[data-action="open-workbench"]').click(); await navigate('risks'); await page.locator('[data-risk-filter="overdue"]').click();
  check((await page.locator('#content').innerText()).includes('提交产品演示材料'), 'specific deadline becomes overdue one minute after cutoff');
  await reset(); await page.setViewportSize({width:390,height:844}); await navigate('today');
  // Force a storage exception to verify behavior, including retrying the same form.
  await page.locator('#add').click(); await page.locator('[name="title"]').fill('失败后重试的事项');
  await page.evaluate(() => { window.originalStorageSet = Storage.prototype.setItem; Storage.prototype.setItem = function(k,v) { if (k === 'virtugene:workbench-design:v1') throw new DOMException('Quota exceeded','QuotaExceededError'); return window.originalStorageSet.call(this,k,v); }; });
  await page.locator('#task-form button[type="submit"]').click();
  check(await page.locator('#task-form').isVisible() && await page.locator('[name="title"]').inputValue() === '失败后重试的事项' && (await page.locator('#toast').innerText()).includes('未能保存'), 'failed save retains input and never reports success');
  check(await read(() => data.tasks.length === 11 && localStorage.getItem('virtugene:workbench-design:v1') === null), 'failed save rolls back memory and leaves persisted data untouched');
  await page.evaluate(() => { Storage.prototype.setItem = window.originalStorageSet; });
  await page.locator('#task-form button[type="submit"]').click();
  check((await state()).tasks.length === 12 && await page.locator('#task-form').count() === 0 && await page.locator('#storage-alert').isHidden(), 'same input can be retried successfully after storage recovers');
  // Export and restore use a real browser download and file input.
  await page.locator('#back').click(); await page.locator('[data-action="data-panel"]').click();
  const downloading = page.waitForEvent('download'); await page.locator('[data-action="export-backup"]').click();
  const download = await downloading, exported = JSON.parse(readFileSync(await download.path(),'utf8'));
  check(exported.format === 'virtugene-workbench-design' && exported.version === 4 && exported.data.tasks.length === 12, 'backup download contains exact isolated state');
  const upload = async value => page.locator('#backup-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(value))});
  const malformed = structuredClone(exported); malformed.data.tasks[0].due = '2026-02-30';
  await upload(malformed); await page.waitForFunction(() => document.querySelector('.backup-message').textContent.includes('校验未通过'));
  check((await state()).tasks.length === 12 && await page.locator('[data-action="confirm-restore"]').count() === 0, 'invalid calendar date is rejected without changing records');
  const duplicate = structuredClone(exported); duplicate.data.tasks.push(duplicate.data.tasks[0]);
  await upload(duplicate); await page.waitForFunction(() => document.getElementById('backup-file').value === ''); check(await page.locator('[data-action="confirm-restore"]').count() === 0, 'duplicate IDs cannot enter restore flow');
  const replacement = structuredClone(exported); replacement.data.tasks = replacement.data.tasks.filter(t => !t.title.includes('失败后重试'));
  await upload(replacement); await page.locator('[data-action="confirm-restore"]').waitFor();
  check((await state()).tasks.length === 12, 'valid backup waits for concrete restore confirmation');
  await page.locator('[data-action="confirm-restore"]').click();
  check((await state()).tasks.length === 11, 'confirmed restore replaces only preview data');
  await page.locator('[data-action="undo"]').click(); check((await state()).tasks.length === 12, 'restore undo brings back preceding data');
  await page.locator('[data-action="open-workbench"]').click();
  // A second page saves first; the stale page must not overwrite it.
  const second = await context.newPage(); await second.goto(url); await second.locator('#add').click();
  await second.locator('[name="title"]').fill('另一个窗口的新安排'); await second.locator('#task-form button[type="submit"]').click();
  await page.locator('#storage-alert').waitFor({state:'visible'});
  await page.locator('#add').click(); await page.locator('[name="title"]').fill('旧窗口的输入'); await page.locator('#task-form button[type="submit"]').click();
  check((await state()).tasks.some(t => t.title === '另一个窗口的新安排') && !(await state()).tasks.some(t => t.title === '旧窗口的输入') && await page.locator('#task-form').isVisible(), 'stale window cannot overwrite newly saved records');
  await second.close(); await page.reload();
  check(await page.locator('#storage-alert').isHidden() && (await state()).tasks.some(t => t.title === '另一个窗口的新安排'), 'reload reconciles latest saved data');
  await page.evaluate(() => { localStorage.setItem('virtugene:workbench-design:v1','{"tasks":[null],"projects":[],"captures":[]}'); }); await page.reload();
  check(await page.locator('#storage-alert').isVisible() && await read(() => localStorage.getItem('virtugene:workbench-design:v1').includes('[null]')), 'malformed stored data stays intact and recovery warning remains visible');
  await page.locator('#add').click(); await page.locator('[name="title"]').fill('不能覆盖原数据'); await page.locator('#task-form button[type="submit"]').click();
  check(await read(() => localStorage.getItem('virtugene:workbench-design:v1').includes('[null]')) && await page.locator('#task-form').isVisible(), 'recovery fallback cannot silently overwrite malformed data');
  await page.keyboard.press('Escape'); await page.locator('#back').click(); await page.locator('.theme-actions [data-action="data-panel"]').click();
  const rawDownload = page.waitForEvent('download'); await page.locator('[data-action="export-raw"]').click();
  check(readFileSync(await (await rawDownload).path(),'utf8').includes('[null]'), 'original malformed bytes can be exported for recovery');
  await page.keyboard.press('Escape'); await page.locator('.demo-actions [data-action="reset-demo"]').click();
  check(await page.locator('#storage-alert').isHidden() && (await state()).tasks.length === 11, 'explicit reset recovers usable preview data');
  for (const width of [320,390,430]) {
    await page.setViewportSize({width,height:740}); await navigate('today'); await page.locator('[data-action="task-center"]').click();
    if ((await page.locator('[data-action="toggle-selection"]').innerText()).includes('批量安排')) await page.locator('[data-action="toggle-selection"]').click();
    check(await page.locator('.sheet').evaluate(el => el.scrollWidth <= el.clientWidth) && await page.locator('.batch-toolbar').evaluate(el => el.getBoundingClientRect().bottom <= innerHeight), `task center keeps batch actions visible at ${width}px on short screen`);
    await page.keyboard.press('Escape');
  }
  await page.setViewportSize({width:390,height:844}); await navigate('projects');
  await page.locator('[data-action="project"][data-id="p3"]').click(); await page.locator('.sheet [data-action="edit"][data-id="t6"]').click();
  await page.locator('#task-form [name="status"]').selectOption('blocked'); await page.locator('#task-form button[type="submit"]').click();
  check((await page.locator('[data-action="project"][data-id="p3"]').innerText()).includes('阻塞') && !(await state()).projects.find(p=>p.id==='p3').blocked, 'blocked task derives project state without overwriting manual project setting');
  await editProject('p3');
  check((await page.locator('#project-form .waiting-hint').innerText()).includes('只修改项目标记不会解除'), 'project edit explains why a blocked task keeps project blocked');
  await page.keyboard.press('Escape'); await page.locator('[data-action="project"][data-id="p3"]').click(); await page.locator('.sheet [data-action="edit"][data-id="t6"]').click();
  await page.locator('#task-form [name="status"]').selectOption('doing'); await page.locator('#task-form button[type="submit"]').click();
  check((await page.locator('[data-action="project"][data-id="p3"]').innerText()).includes('正常'), 'resolving last blocked task returns derived project status to normal');
  await reset();
  await page.evaluate(() => { data.tasks.find(t => t.id === 't6').focusDate = '2026-09-18'; data.tasks.find(t => t.id === 't7').focusDate = '2026-09-17'; data.tasks.find(t => t.id === 't2').focusDate = '2026-10-04'; save(); render(false); });
  await page.locator('[data-action="task-center"]').click(); await page.locator('[data-center-status="expired-focus"]').click();
  check(await page.locator('.task-center-row').count() === 2 && (await page.locator('#task-center-results').innerText()).includes('2026-09-18'), 'expired focus includes arbitrarily old incomplete focus and excludes completed or future focus');
  await snapshot('expired-focus');
  if ((await page.locator('[data-action="toggle-selection"]').innerText()).includes('批量安排')) await page.locator('[data-action="toggle-selection"]').click();
  await page.locator('[data-select-task="t6"]').check(); await page.locator('[data-action="batch-clear-focus"]').click();
  check((await state()).tasks.find(t => t.id === 't6').focusDate === '' && (await state()).tasks.find(t => t.id === 't6').status === 'todo' && (await state()).tasks.find(t => t.id === 't11').focusDate === '2026-10-02', 'clearing selected expired focus keeps tasks and leaves unselected dates intact');
  await page.locator('[data-action="undo"]').click();
  check(await page.locator('.task-center-row').count() === 2 && (await state()).tasks.find(t => t.id === 't6').focusDate === '2026-09-18', 'cleared focus can be restored atomically');
  await page.locator('[data-select-task="t6"]').check(); await page.locator('[data-action="batch-focus"]').click();
  check((await state()).tasks.find(t => t.id === 't6').focusDate === '2026-10-03' && await page.locator('.task-center-row').count() === 1, 'older focus can be explicitly carried to today without remaining in expired filter');
  await reset(); await navigate('risks'); await page.locator('[data-risk-filter="waiting"]').click();
  await page.locator('[data-action="quick-followup"][data-task-id="t4"]').click();
  await page.locator('[data-followup-date="2026-10-06"]').click(); await page.locator('#followup-form button[type="submit"]').click();
  check((await state()).events.filter(e => e.kind === 'followup-planned').length === 1 && (await state()).events.find(e => e.kind === 'followup-planned').previousFollowup === '2026-10-02', 'followup schedule and old value are stored as one planning event');
  await navigate('week');
  check(await page.locator('.week-stats strong').first().textContent() === '4' && await page.locator('.followup-result').count() === 0 && (await page.locator('.followup-plans summary').innerText()).includes('1 次'), 'planning event appears separately and never counts as completion or actual contact');
  await navigate('today'); await page.locator('[data-action="task-center"]').click(); await page.locator('.task-center [data-action="edit"][data-id="t4"]').click();
  await page.locator('#task-form button[type="submit"]').click();
  check((await state()).events.filter(e => e.kind === 'followup-planned').length === 1, 'unchanged followup fields do not create another plan event');
  await page.locator('.task-center [data-action="edit"][data-id="t4"]').click();
  await page.locator('[data-action="record-followup"]').click();
  await page.locator('#record-followup-form [name="at"]').fill('2026-10-04'); await page.locator('#record-followup-form [name="note"]').fill('已电话联系，预算仍在审批');
  await page.locator('#record-followup-form button[type="submit"]').click();
  check(await page.locator('#record-followup-form').isVisible() && (await state()).events.length === 5, 'future actual-contact dates cannot be confirmed or stored');
  await page.locator('#record-followup-form [name="at"]').fill('2026-09-25');
  await page.evaluate(() => { window.originalStorageSet = Storage.prototype.setItem; Storage.prototype.setItem = function(k,v) { if (k === 'virtugene:workbench-design:v1') throw new DOMException('Quota exceeded','QuotaExceededError'); return window.originalStorageSet.call(this,k,v); }; });
  await page.locator('#record-followup-form button[type="submit"]').click();
  check(await page.locator('#record-followup-form').isVisible() && (await state()).events.length === 5 && await page.locator('#record-followup-form [name="note"]').inputValue() === '已电话联系，预算仍在审批', 'failed actual-contact write preserves input and does not leave a partial event');
  await page.evaluate(() => { Storage.prototype.setItem = window.originalStorageSet; }); await page.locator('#record-followup-form button[type="submit"]').click();
  const actualEvent = (await state()).events.find(e => e.kind === 'followup-recorded');
  check(actualEvent.at === '2026-09-25' && actualEvent.recordedOn === '2026-10-03' && (await state()).tasks.find(t => t.id === 't4').followup === '2026-10-06' && (await state()).tasks.find(t => t.id === 't4').status === 'waiting', 'backdated contact stores actual and entry dates without changing the reminder or lifecycle');
  await page.locator('[data-action="undo"]').click();
  check((await state()).events.filter(e => e.kind === 'followup-recorded').length === 0 && (await state()).events.filter(e => e.kind === 'followup-planned').length === 1, 'undo actual contact removes only the new event');
  await page.locator('[data-action="task-center"]').click(); await page.locator('.task-center [data-action="edit"][data-id="t4"]').click(); await page.locator('[data-action="record-followup"]').click();
  await page.locator('#record-followup-form [name="at"]').fill('2026-09-25'); await page.locator('#record-followup-form [name="note"]').fill('已电话联系，预算仍在审批'); await page.locator('#record-followup-form button[type="submit"]').click();
  await navigate('week');
  check(await page.locator('.followup-result').count() === 0, 'backdated contact does not inflate the entry-week contact count');
  await page.locator('[data-action="previous-week"]').click();
  check((await page.locator('.followup-result').innerText()).includes('已电话联系') && (await page.locator('#content').innerText()).includes('补记于 2026-10-03') && await page.locator('.week-stats strong').first().textContent() === '0', 'actual-week review shows backdated contact and entry-date disclosure separately from completions');
  await page.locator('#toast').evaluate(el => { el.innerHTML = ''; }); await snapshot('followup-history');
  await page.locator('[data-action="review"]').click();
  check((await page.locator('#review-text').inputValue()).includes('2026-09-25 跟进客户的预算确认') && (await page.locator('#review-text').inputValue()).includes('本周跟进（已发生'), 'editable review draft includes actual followup facts');
  await page.keyboard.press('Escape'); await navigate('today'); await page.locator('[data-action="task-center"]').click(); await page.locator('.task-center [data-action="edit"][data-id="t4"]').click();
  await page.locator('#task-form [name="title"]').fill('现在改名的客户事项'); await page.locator('#task-form [name="followup"]').fill(''); await page.locator('#task-form button[type="submit"]').click(); await page.keyboard.press('Escape');
  check((await state()).events.filter(e => e.kind === 'followup-planned').length === 2 && (await state()).events.find(e => e.kind === 'followup-planned' && !e.followup).previousFollowup === '2026-10-06', 'clearing a planned reminder is recorded with its former date');
  await navigate('week');
  check((await page.locator('.followup-result').innerText()).includes('已电话联系') && (await page.locator('#content').innerText()).includes('跟进客户的预算确认') && !(await page.locator('.followup-result').innerText()).includes('现在改名'), 'task renaming does not rewrite historic contact snapshot');
  await page.reload(); await navigate('week'); await page.locator('[data-action="previous-week"]').click();
  check(await page.locator('.followup-result').count() === 1, 'contact events survive reload and remain queryable by actual date');
  await navigate('today'); await page.locator('[data-action="task-center"]').click(); await page.locator('.task-center [data-action="edit"][data-id="t4"]').click(); await page.locator('[data-action="record-followup"]').click();
  await page.locator('#record-followup-form [name="at"]').fill('2026-09-25'); await page.locator('#record-followup-form [name="note"]').fill('第二次联系，仍待审批'); await page.locator('#record-followup-form button[type="submit"]').click(); await navigate('week');
  check(await page.locator('.followup-result').count() === 2, 'two real contacts for the same task on the same day remain two distinct events');
  await page.locator('#back').click(); await page.locator('[data-action="data-panel"]').click();
  const eventsDownload = page.waitForEvent('download'); await page.locator('[data-action="export-backup"]').click();
  const withEvents = JSON.parse(readFileSync(await (await eventsDownload).path(),'utf8'));
  check(withEvents.version === 4 && withEvents.data.events.some(e => e.kind === 'followup-recorded'), 'v4 backup preserves actual-contact event kind');
  const badKind = structuredClone(withEvents); badKind.data.events[0].kind = 'invented';
  await page.locator('#backup-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(badKind))});
  await page.waitForFunction(() => document.getElementById('backup-file').value === '');
  check(await page.locator('[data-action="confirm-restore"]').count() === 0 && (await state()).events.some(e=>e.kind==='followup-recorded'), 'unknown event kinds are rejected without replacing history');
  const badDate = structuredClone(withEvents); badDate.data.events.find(e => e.kind === 'followup-recorded').at = '2026-10-04';
  await page.locator('#backup-file').setInputFiles({name:'future-fact.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(badDate))}); await page.waitForFunction(() => document.getElementById('backup-file').value === '');
  check(await page.locator('[data-action="confirm-restore"]').count() === 0, 'restore rejects actual-contact dates after their recorded date');
  const missingKind = structuredClone(withEvents); delete missingKind.data.events[0].kind;
  await page.locator('#backup-file').setInputFiles({name:'missing-kind.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(missingKind))}); await page.waitForFunction(() => document.getElementById('backup-file').value === '');
  check(await page.locator('[data-action="confirm-restore"]').count() === 0, 'v4 requires explicit event kinds instead of guessing new event meaning');
  const legacy = structuredClone(withEvents); legacy.version = 3; legacy.data.events = legacy.data.events.filter(e=>e.kind==='completed'); legacy.data.events.forEach(e=>delete e.kind);
  await page.locator('#backup-file').setInputFiles({name:'legacy-v3.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(legacy))}); await page.locator('[data-action="confirm-restore"]').click();
  await page.locator('[data-action="open-workbench"]').click(); await navigate('week');
  check(await page.locator('.week-stats strong').first().textContent() === '4' && await page.locator('.followup-result').count() === 0, 'v3 completion-only backup restores without manufacturing contact history');
  await page.locator('#back').click(); await page.locator('[data-action="data-panel"]').click();
  const migratedDownload = page.waitForEvent('download'); await page.locator('[data-action="export-backup"]').click();
  const migrated = JSON.parse(readFileSync(await (await migratedDownload).path(),'utf8'));
  check(migrated.version === 4 && migrated.data.events.every(e=>e.kind==='completed'), 'export upgrades legacy completion events to explicit v4 kinds without adding contact facts');
  await page.keyboard.press('Escape'); await page.locator('[data-action="open-workbench"]').click();
  await navigate('inbox');
  const beforeConfirmation = JSON.stringify(await state());
  await page.locator('[data-action="capture-confirmation-preview"]').click();
  check(await page.getByRole('dialog',{name:'助理整理确认卡片 · 样式预览'}).isVisible() && await page.getByRole('button',{name:'确认加入 · 仅展示样式'}).isDisabled() && JSON.stringify(await state()) === beforeConfirmation, 'assistant confirmation preview makes uncertainty explicit and cannot write demo candidates');
  await snapshot('capture-confirmation'); await page.keyboard.press('Escape');
  await reset(); await navigate('today'); await page.locator('#add').click();
  await page.locator('#task-form [name="title"]').fill('新建后校验跟进日期'); await page.locator('#task-form [name="status"]').selectOption('waiting');
  await page.locator('#task-form button[type="submit"]').click();
  const createdTask = (await state()).tasks.find(t=>t.title==='新建后校验跟进日期');
  check(createdTask.createdDate === '2026-10-03', 'new demo tasks record their actual demo creation date');
  await page.locator('[data-action="task-center"]').click(); await page.locator(`.task-center [data-action="edit"][data-id="${createdTask.id}"]`).click(); await page.locator('[data-action="record-followup"]').click();
  check(await page.locator('#record-followup-form [name="at"]').getAttribute('min') === '2026-10-03' && await page.locator('#record-followup-form [name="at"]').inputValue() === '2026-10-03', 'known task creation date bounds and defaults the actual-contact field');
  await page.locator('#record-followup-form [name="at"]').fill('2026-10-02'); await page.locator('#record-followup-form [name="note"]').fill('尝试创建前日期');
  const eventsBeforeNew = (await state()).events.length;
  await page.locator('#record-followup-form button[type="submit"]').click();
  check(await page.locator('#record-followup-form').isVisible() && (await state()).events.length === eventsBeforeNew, 'native lower-date constraint prevents impossible new-task contact');
  await page.locator('#record-followup-form').evaluate(form=>form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
  check((await state()).events.length === eventsBeforeNew, 'business validation also rejects dates before known creation');
  await page.locator('#record-followup-form [name="at"]').fill('2026-10-03'); await page.locator('#record-followup-form [name="method"]').selectOption('other');
  check(await page.locator('#followup-method-detail').isVisible(), 'other contact method reveals a custom description field');
  await page.locator('#record-followup-form button[type="submit"]').click();
  check((await state()).events.length === eventsBeforeNew && await page.locator('#record-followup-form').isVisible(), 'new other-method contact requires a specific description');
  await page.locator('#record-followup-form [name="methodDetail"]').fill('工单 <协作> & 反馈'); await page.locator('#record-followup-form [name="note"]').fill('已在工单中留言，等待审批');
  await page.locator('#toast').evaluate(el => { el.innerHTML = ''; }); await snapshot('followup-record');
  await page.locator('#record-followup-form button[type="submit"]').click();
  const customEvent = (await state()).events.find(e=>e.taskId===createdTask.id && e.kind==='followup-recorded');
  check(customEvent.method === 'other' && customEvent.methodDetail === '工单 <协作> & 反馈' && customEvent.taskCreatedDate === '2026-10-03', 'custom method keeps stable enum and records known creation snapshot');
  await navigate('week');
  check((await page.locator('#content').innerText()).includes('其他 · 工单 <协作> & 反馈'), 'custom method is rendered as safe text with its original characters');
  await page.locator('[data-action="review"]').click();
  check((await page.locator('#review-text').inputValue()).includes('其他 · 工单 <协作> & 反馈'), 'review draft includes literal custom method rather than HTML escaping');
  await page.keyboard.press('Escape'); await navigate('today'); await page.locator('[data-action="task-center"]').click(); await page.locator('.task-center [data-action="edit"][data-id="t4"]').click(); await page.locator('[data-action="record-followup"]').click();
  check(await page.locator('#record-followup-form [name="at"]').getAttribute('min') === null && (await page.locator('#record-followup-form').innerText()).includes('创建日期未知'), 'legacy tasks keep unknown creation date without invented lower bound');
  await page.locator('#record-followup-form [name="at"]').fill('2026-09-20'); await page.locator('#record-followup-form [name="method"]').selectOption('other'); await page.locator('#record-followup-form [name="methodDetail"]').fill('视频会议'); await page.locator('#record-followup-form [name="method"]').selectOption('phone');
  check(await page.locator('#followup-method-detail').isHidden() && await page.locator('#record-followup-form [name="methodDetail"]').isDisabled(), 'switching back to a standard method disables hidden custom input');
  await page.locator('#record-followup-form [name="note"]').fill('补记历史任务的电话跟进'); await page.locator('#record-followup-form button[type="submit"]').click();
  check((await state()).events.some(e=>e.taskId==='t4' && e.at==='2026-09-20' && e.method==='phone' && !e.methodDetail && !e.taskCreatedDate), 'legacy unknown creation still allows factual backdating without stale method metadata');
  const finalBackup = {format:'virtugene-workbench-design',version:4,data:await state()};
  const invalidCreation = structuredClone(finalBackup); invalidCreation.data.events.find(e=>e.taskId===createdTask.id && e.kind==='followup-recorded').at='2026-10-02';
  check(await page.evaluate(value=>WorkbenchData.validate(value)===null,invalidCreation), 'restore validation rejects contact dates before recorded creation snapshot');
  const invalidDetail = structuredClone(finalBackup); invalidDetail.data.events.find(e=>e.kind==='followup-recorded').methodDetail='x'.repeat(41);
  check(await page.evaluate(value=>WorkbenchData.validate(value)===null,invalidDetail), 'restore rejects oversized method descriptions');
  check(await page.evaluate(value=>!!WorkbenchData.validate(value),finalBackup), 'v4 round trip preserves optional method and creation fields');
  await page.reload();
  check((await state()).events.some(e=>e.methodDetail==='工单 <协作> & 反馈') && (await state()).tasks.find(t=>t.id==='t4').createdDate===undefined, 'reload preserves custom methods without inventing legacy task creation');
  check(errors.length === 0, `browser has no runtime errors: ${errors.join(', ')}`);
  check(failed.length === 0, `local assets load: ${failed.join(', ')}`);
  await reset();
  console.log(`Workbench design: ${checks} checks passed. Screenshots: ${artifacts}`);
} finally { await browser.close(); await new Promise(r => server.close(r)); }
