"""Build local variable WOFF2 subsets from the upstream Noto Sans SC font.

Usage: python scripts/build-ui-font.py /path/to/NotoSansSC[wght].ttf
Requires fonttools[woff] (build tooling only, not an app dependency).
"""
from pathlib import Path
import sys
from fontTools import subset
from fontTools.ttLib import TTFont

root = Path(__file__).resolve().parent.parent
source = Path(sys.argv[1])
destination = root / 'src/assets/fonts'
destination.mkdir(parents=True, exist_ok=True)
font = TTFont(source)
available = set(font.getBestCmap())
font.close()

# Put shipped UI glyphs in one small file; all other supported glyphs still ship.
common = set(range(0x20, 0x250)) | set(range(0x2000, 0x2070)) | set(range(0x3000, 0x3040))
for file in (root / 'src').rglob('*'):
    if file.suffix in {'.ts', '.tsx'}:
        common.update(ord(char) for char in file.read_text(encoding='utf-8') if '\u2e80' <= char <= '\uffef')
common &= available
remaining = sorted(available - common)

def ranges(points):
    result = []
    for cp in sorted(points):
        if result and cp == result[-1][1] + 1:
            result[-1][1] = cp
        else:
            result.append([cp, cp])
    return ','.join(f'U+{a:X}' + (f'-{b:X}' if a != b else '') for a, b in result)

def build(name, points, unicode_range):
    font = TTFont(source)
    options = subset.Options()
    options.flavor = 'woff2'
    options.hinting = False
    options.layout_features = ['kern', 'liga', 'clig', 'calt', 'locl', 'rlig', 'tnum', 'pnum']
    options.name_IDs = ['*']
    tool = subset.Subsetter(options=options)
    tool.populate(unicodes=points)
    tool.subset(font)
    font.flavor = 'woff2'
    output = destination / name
    font.save(output)
    font.close()
    print(f'{name}: {len(points)} codepoints, {output.stat().st_size:,} bytes', flush=True)
    return f'''@font-face {{
  font-family:"VG Sans"; font-style:normal; font-weight:100 900; font-display:swap;
  src:url("../assets/fonts/{name}") format("woff2");
  unicode-range:{unicode_range};
}}\n'''

css = '/* Generated by scripts/build-ui-font.py. Common UI glyphs come last so they win range overlap. */\n'
for index, start in enumerate(range(0, len(remaining), 4000)):
    points = remaining[start:start + 4000]
    css += build(f'noto-sans-sc-extra-{index + 1}.woff2', points, f'U+{points[0]:X}-{points[-1]:X}')
css += build('noto-sans-sc-ui.woff2', common, ranges(common))
(root / 'src/styles/ui-fonts.css').write_text(css, encoding='utf-8')
license_file = source.with_name('OFL.txt')
if license_file.exists():
    (destination / 'OFL-NotoSansSC.txt').write_text(license_file.read_text(encoding='utf-8'), encoding='utf-8')
print(f'Total WOFF2: {sum(f.stat().st_size for f in destination.glob("*.woff2")):,} bytes', flush=True)
